using Notary.SSAA.BO.Domain.Entities;

namespace Notary.SSAA.BO.WebApi.Seeds.SignRequest.Entities.Fingerprint
{
    public class PersonFingerprintCollection
    {
        public static List<PersonFingerprint> GetSeedData()
        {
            return new List<PersonFingerprint>
            {
                new PersonFingerprint
                {
                    Id = Guid.Parse("88dc87de-6081-4271-b232-440801c04dba"),
                    OrganizationId = "57999",
                    PersonFingerprintUseCaseId = "1",
                    UseCasePersonObjectId = "e731dbde-b900-4bcc-ae6d-3cfff332aa30",
                    PersonNationalNo = "1234567890",
                    NameFamily = "محمد محمدی",
                    PersonFingerTypeId = "1",
                    SmartCardStatus = null,
                    SmartCardRequestDate = null,
                    SmartCardRequestTime = null,
                    SmartCardResponseDate = null,
                    SmartCardResponseTime = null,
                    MocIsRequired = "2",
                    MocState = null,
                    MocDescription = null,
                    FingerprintImageFile = new byte[] { 0x01, 0x02, 0x03, 0x04, 0x05 },
                    FingerprintImageType = "JPEG",
                    FingerprintImageHeight = 480,
                    FingerprintImageWidth = 320,
                    FingerprintFeatures = null,
                    FingerprintScannerDeviceType = "futronicfs88",
                    FingerprintGetDate = "1404/06/09",
                    FingerprintGetTime = "11:20:34",
                    TfaMobileNo = "09123712404",
                    TfaIsRequired = "1",
                    TfaValue = null,
                    TfaSendDate = null,
                    TfaSendTime = null,
                    TfaValidateDate = null,
                    TfaValidateTime = null,
                    TfaState = null,
                    Description = null,
                    IsDeleted = "1",
                    Ilm = "1", // fixed
                    LegacyId = null,
                    RecordDate = null,
                    UseCaseMainObjectId = "62f720b6-c03b-4dfd-908e-cff35e8c6bed",
                    FingerprintRawImage = null,
                    State = "1",
                    IsRemoteRequest = null
                },
                new PersonFingerprint
                {
                    Id = Guid.Parse("99ed98ef-7192-5382-c343-551912d15ecb"),
                    OrganizationId = "57999",
                    PersonFingerprintUseCaseId = "1",
                    UseCasePersonObjectId = "870ec471-7e8e-4d50-a53e-b9855471750f",
                    PersonNationalNo = "1234567891",
                    NameFamily = "زهرا رضایی",
                    PersonFingerTypeId = "2",
                    SmartCardStatus = null,
                    SmartCardRequestDate = null,
                    SmartCardRequestTime = null,
                    SmartCardResponseDate = null,
                    SmartCardResponseTime = null,
                    MocIsRequired = "1",
                    MocState = null,
                    MocDescription = null,
                    FingerprintImageFile = new byte[] { 0x06, 0x07, 0x08, 0x09, 0x0A },
                    FingerprintImageType = "JPEG",
                    FingerprintImageHeight = 480,
                    FingerprintImageWidth = 320,
                    FingerprintFeatures = null,
                    FingerprintScannerDeviceType = "futronicfs88",
                    FingerprintGetDate = "1404/06/10",
                    FingerprintGetTime = "10:15:22",
                    TfaMobileNo = "09124567890",
                    TfaIsRequired = "1",
                    TfaValue = null,
                    TfaSendDate = null,
                    TfaSendTime = null,
                    TfaValidateDate = null,
                    TfaValidateTime = null,
                    TfaState = null,
                    Description = null,
                    IsDeleted = "0",
                    Ilm = "1", // fixed
                    LegacyId = null,
                    RecordDate = null,
                    UseCaseMainObjectId = "62f720b6-c03b-4dfd-908e-cff35e8c6bed",
                    FingerprintRawImage = null,
                    State = "1",
                    IsRemoteRequest = null
                },
                new PersonFingerprint
                {
                    Id = Guid.Parse("aafeaaf0-82a3-6493-d454-662a23e26fdc"),
                    OrganizationId = "57999",
                    PersonFingerprintUseCaseId = "1",
                    UseCasePersonObjectId = "f98ddfac-81fc-431a-b9ae-8f1e8be58e40",
                    PersonNationalNo = "1234567892",
                    NameFamily = "مریم جعفری",
                    PersonFingerTypeId = "3",
                    SmartCardStatus = null,
                    SmartCardRequestDate = null,
                    SmartCardRequestTime = null,
                    SmartCardResponseDate = null,
                    SmartCardResponseTime = null,
                    MocIsRequired = "2",
                    MocState = null,
                    MocDescription = null,
                    FingerprintImageFile = new byte[] { 0x0B, 0x0C, 0x0D, 0x0E, 0x0F },
                    FingerprintImageType = "JPEG",
                    FingerprintImageHeight = 480,
                    FingerprintImageWidth = 320,
                    FingerprintFeatures = null,
                    FingerprintScannerDeviceType = "futronicfs88",
                    FingerprintGetDate = "1404/06/11",
                    FingerprintGetTime = "14:30:45",
                    TfaMobileNo = "09123456789",
                    TfaIsRequired = "0",
                    TfaValue = null,
                    TfaSendDate = null,
                    TfaSendTime = null,
                    TfaValidateDate = null,
                    TfaValidateTime = null,
                    TfaState = null,
                    Description = null,
                    IsDeleted = "0",
                    Ilm = "1", // fixed
                    LegacyId = null,
                    RecordDate = null,
                    UseCaseMainObjectId = "62f720b6-c03b-4dfd-908e-cff35e8c6bed",
                    FingerprintRawImage = null,
                    State = "1",
                    IsRemoteRequest = null
                },
                new PersonFingerprint
                {
                    Id = Guid.Parse("bb0fbbb1-93b4-75a4-e565-773b34f37aed"),
                    OrganizationId = "57999",
                    PersonFingerprintUseCaseId = "1",
                    UseCasePersonObjectId = "2d6345ff-dafa-4a11-c233-6a1125b359ab",
                    PersonNationalNo = "0012254986",
                    NameFamily = "سارا حسینی",
                    PersonFingerTypeId = "4",
                    SmartCardStatus = null,
                    SmartCardRequestDate = null,
                    SmartCardRequestTime = null,
                    SmartCardResponseDate = null,
                    SmartCardResponseTime = null,
                    MocIsRequired = "1",
                    MocState = null,
                    MocDescription = null,
                    FingerprintImageFile = new byte[] { 0x10, 0x11, 0x12, 0x13, 0x14 },
                    FingerprintImageType = "JPEG",
                    FingerprintImageHeight = 480,
                    FingerprintImageWidth = 320,
                    FingerprintFeatures = null,
                    FingerprintScannerDeviceType = "futronicfs88",
                    FingerprintGetDate = "1404/06/12",
                    FingerprintGetTime = "09:45:18",
                    TfaMobileNo = "09129876543",
                    TfaIsRequired = "1",
                    TfaValue = null,
                    TfaSendDate = null,
                    TfaSendTime = null,
                    TfaValidateDate = null,
                    TfaValidateTime = null,
                    TfaState = null,
                    Description = null,
                    IsDeleted = "0",
                    Ilm = "1", // fixed
                    LegacyId = null,
                    RecordDate = null,
                    UseCaseMainObjectId = "62f720b6-c03b-4dfd-908e-cff35e8c6bed",
                    FingerprintRawImage = null,
                    State = "1",
                    IsRemoteRequest = null
                }
            };
        }
    }
}
