

namespace Notary.SSAA.BO.SharedKernel.SharedModels.DocumentReport
{
    public class DocumentReportViewModel
    {
        public DocumentReportViewModel()
        {
            documentReportItems = new List<DocumentReportItem>();
        }
        public IList<DocumentReportItem> documentReportItems { get; set; }
       
    }

    public class DocumentReportItem
    {
        public string MainPersonId { get; set; }
        public string MainPersonAddress { get; set; }
        public string MainPersonBirthDate { get; set; }
        public string MainPersonCompanyRegisterDate { get; set; }
        public string MainPersonCompanyRegisterLocation { get; set; }
        public string MainPersonCompanyRegisterNo { get; set; }
        public string MainPersonFamily { get; set; }
        public string MainPersonName { get; set; }
        public string MainPersonFatherName { get; set; }
        public string MainPersonIdentityIssueLocation { get; set; }
        public string MainPersonIdentityNo { get; set; }
        public string MainPersonIsOrginal { get; set; }
        public string MainPersonLastLegalPaperDate { get; set; }
        public string MainPersonLastLegalPaperNo { get; set; }
        public string MainLegalPersonNatureId { get; set; }
        public string MainLegalPersonTypeId { get; set; }
        public string MainPersonCompanyTypeId { get; set; }
        public string MainPersonIsIranian { get; set; }
        public string MainPersonNationalNo { get; set; }
        public string MainPersonNationalityId { get; set; }
        public string MainPersonNationality { get; set; }
        public string MainPersonTypeId { get; set; }
        public string MainPersonPostalCode { get; set; }
        public string MainPersonSexType { get; set; }
        public string MainPersonTel { get; set; }
        public string MainPersonRowNo { get; set; }
        public string MainPersonDescription { get; set; }
        public string MainPersonType { get; set; }
        public string PersonTypeSingularTitle { get; set; }
        public string PersonTypePluralTitle { get; set; }
        public string PersonTypePrintSingularTitle { get; set; }
        public string PersonTypePrintPluralTitle { get; set; }
        public string IsOwner { get; set; }
        public string PersonFingerPrintImageFile { get; set; }
        public string AgentPersonId { get; set; }
        public string AgentPersonName { get; set; }
        public string AgentPersonFamily { get; set; }
        public string AgentTypeCode { get; set; }
        public string AgentTypeTitle { get; set; }
        public string MainAgentPersonId { get; set; }
        public string AgentTypeRoot { get; set; }
        public string ReliablePersonReasonCode { get; set; }
        public string RelatedAgentDocumentNo { get; set; }
        public string RelatedAgentDocumentDate { get; set; }
        public string RelatedAgentDocumentIssuer { get; set; }
        public string DocumentId { get; set; }
        public string ScriptoriumId { get; set; }
        public string DocumentDate { get; set; }
        public string RequestDate { get; set; }
        public string RequestTime { get; set; }
        public string ClassifyNo { get; set; }
        public string DocumentSecretCode { get; set; }
        public string GetDocumentNoDate { get; set; }
        public string DocumentNationalNo { get; set; }
        public string BookVolumeNo { get; set; }
        public string BookPaperType { get; set; }
        public string DocumentPrice { get; set; }
        public string DocumentSabtPrice { get; set; }
        public string DocumentSignDate { get; set; }
        public string DocumentSignTime { get; set; }
        public string OtherDocumentTypeTitle { get; set; }
        public string DocumentState { get; set; }
        public string IsBaseJudgment { get; set; }
        public string DocumentTypeId { get; set; }
        public string DocumentTypeTitle { get; set; }
        public string DocumentTypeCaseTitle { get; set; }
        public string DocumentTypeIsSupportive { get; set; }
        public string WealthType { get; set; }
        public string HasAsset { get; set; }
        public string SardaftarConfirmDate { get; set; }
        public string DaftaryarConfirmDate { get; set; }
        public string SardaftarConfirmFullName { get; set; }
        public string DaftaryarConfirmFullName { get; set; }
        public string ConfirmDate { get; set; }
        public string ConfirmCreateDate { get; set; }
        public string CreatorNameFamily { get; set; }
        public string TextFontSize { get; set; }
        public string DocumentTextDescription { get; set; }
        public string TextPrintMode { get; set; }
        public string LegalText { get; set; }
        public string HasMultipleAdvocacyPermit { get; set; }
        public string IsDocumentBrief { get; set; }
        public string DividedSectionsCount { get; set; }
        public string RegisterCount { get; set; }
        public string HasDismissalPermit { get; set; }
        public string HasAdvocacyToOthersPermit { get; set; }
        public string HasTime { get; set; }
        public string AdvocacyEndDate { get; set; }
        public string RentStartDate { get; set; }
        public string RentDuration { get; set; }
        public string IsPeaceForLifeTime { get; set; }
        public string PeaceDuration { get; set; }
        public string HagheEntefae { get; set; }
        public string VaghfType { get; set; }
        public string IsRentWithSarghofli { get; set; }
        public string MortageDuration { get; set; }
        public string MortageTimeUnitId { get; set; }
        public string JudgmentIssueDate { get; set; }
        public string JudgmentIssueName { get; set; }
        public string JudgmentIssueNo { get; set; }
        public string JudgmentIssueCaseClassifyNo { get; set; }
        public string JudmentTypeId { get; set; }
        public string JudmentTypeTitle { get; set; }
        public string CostPrice { get; set; }
        public string CostTypeId { get; set; }
        public string CostTypeTitle { get; set; }
        public string EstateId { get; set; }
        public string EstateDescription { get; set; }
        public string EstateAddress { get; set; }
        public string EstateArea { get; set; }
        public string EstateAreaDescription { get; set; }
        public string EstateTypeId { get; set; }
        public string EstateTypeTitle { get; set; }
        public string EstatePrice { get; set; }
        public string EstateSectionId { get; set; }
        public string EstateBasicPlaque { get; set; }
        public string EstateBasicPlaqueHasRemain { get; set; }
        public string EstateBlock { get; set; }
        public string EstateCommons { get; set; }
        public string EstateDirection { get; set; }
        public string EstateDivFromBasicPlaque { get; set; }
        public string EstateDivFromSecondaryPlaque { get; set; }
        public string EstateFloor { get; set; }
        public string EstateGeoLocationId { get; set; }
        public string EstateSubSectionId { get; set; }
        public string EstateEvacuationDescription { get; set; }
        public string EstateImmovaleType { get; set; }
        public string EstateLimits { get; set; }
        public string EstateLocationType { get; set; }
        public string EstateUnitId { get; set; }
        public string EstateOldSaleDescription { get; set; }
        public string EstatePiece { get; set; }
        public string EstatePlaqueText { get; set; }
        public string EstateSecondaryPlaqueHasRemain { get; set; }
        public string EstateSecondaryPlaque { get; set; }
        public string EstateMunicipalityNo { get; set; }
        public string EstateMunicipalityDate { get; set; }
        public string EstateMunicipalityIssuer { get; set; }
        public string EstateSeprationDate { get; set; }
        public string EstateSeprationNo { get; set; }
        public string EstateSeprationIssuer { get; set; }
        public string EstateQuotaText { get; set; }
        public string EstateReceiverBasicPlaque { get; set; }
        public string EstateReceiverBasicPlaqueHasRemain { get; set; }
        public string EstateReceiverDivFromBasicPlaque { get; set; }
        public string EstateReceiverDivFromSecondaryPlaque { get; set; }
        public string EstateReceiverPlaqueText { get; set; }
        public string EstateReceiverSecondaryPlaqueHasRemain { get; set; }
        public string EstateIsRemortage { get; set; }
        public string EstateAttachmentSpecifications { get; set; }
        public string EstateAttachmentDescription { get; set; }
        public string EstateAttachmentType { get; set; }
        public string EstateAttachmentTypeOther { get; set; }
        public string EstateIsAttachment { get; set; }
        public string EstateSellDetailQuota { get; set; }
        public string EstateSellTotalQuota { get; set; }
        public string EstateIsProportionateQuota { get; set; }
        public string EstateIsRegistered { get; set; }
        public string EstateQuotaDetailQuota { get; set; }
        public string EstateQuotaTotalQuota { get; set; }
        public string EstateQuotaPersonId { get; set; }
        public string EstateSectionTitle { get; set; }
        public string EstateSubSectionTitle { get; set; }

        public string EstateQuotaDetailSellerPersonId { get; set; }
        public string EstateQuotaDetailBuyerPersonId { get; set; }
        public string EstateQuotaDetailSellerDetailQuota { get; set; }
        public string EstateQuotaDetailSellerTotalQuota { get; set; }
        public string EstateQuotaDetailByuerDetailQuota { get; set; }
        public string EstateQuotaDetailByuerTotalQuota { get; set; }
        public string EstateQuotaDetailQuotaText { get; set; }
        public string EstateQuotaDetailOwnerShipTotalQuota { get; set; }
        public string EstateQuotaDetailOwnerShipDetailQuota { get; set; }
        public string DocumentInquiryReplyDetailQuota { get; set; }
        public string DocumentInquiryReplyTotalQuota { get; set; }
        public string DocumentInquiryReplyQuotaText { get; set; }
        public string DocumentInquiryPersonId { get; set; }
        public string VehicleCardNo { get; set; }
        public string VehicleChassisNo { get; set; }
        public string VehicleColor { get; set; }
        public string VehicleCylinderCount { get; set; }
        public string VehicleDutyFicheNo { get; set; }
        public string VehicleEngineCapacity { get; set; }
        public string VehicleEngineNo { get; set; }
        public string VehicleNumberingLocation { get; set; }
        public string VehicleOtherInfo { get; set; }
        public string VehicleInssuranceCo { get; set; }
        public string VehicleInssuranceNo { get; set; }
        public string VehicleOldDocumentDate { get; set; }
        public string VehicleOldDocumentIssuer { get; set; }
        public string VehicleOldDocumentNo { get; set; }
        public string VehiclePlaqueNoAlphaBuyer { get; set; }
        public string VehiclePlaqueNoAlphaSeller { get; set; }
        public string VehiclePlaqueNo1Seller { get; set; }
        public string VehiclePlaqueNo1Buyer { get; set; }
        public string VehiclePlaqueNo2Seller { get; set; }
        public string VehiclePlaqueNo2Buyer { get; set; }
        public string VehiclePlaqueSeriSeller { get; set; }
        public string VehiclePlaqueSeriBuyer { get; set; }
        public string VehiclePlaqueSeller { get; set; }
        public string VehicleTipTitle { get; set; }
        public string VehicleQuotaDetailSellerPersonId { get; set; }
        public string VehicleQuotaDetailBuyerPersonId { get; set; }
        public string VehicleQuotaDetailSellerDetailQuota { get; set; }
        public string VehicleQuotaDetailSellerTotalQuota { get; set; }
        public string VehicleQuotaDetailQuotaText { get; set; }
        public string VehicleQuotaDetailQuota { get; set; }
        public string VehicleQuotaTotalQuota { get; set; }
        public string VehicleQuotaQuotaText { get; set; }
        public string VehicleQuotaPersonId { get; set; }
        public string VehicleQuotaDetailBuyerDetailQuota { get; set; }
        public string VehicleQuotaDetailBuyerTotalQuota { get; set; }
        public string VehicleOwnershipPrintedDocumentNo {  get; set; }
        //public string EstateSeprationPiecesUnitId { get; set; }
        public string DocumentVehicleId { get; set; }
        public string EstateSeprationPiecesArea { get; set;}
        public string EstateSeprationPiecesNo { get; set; }
        public string EstatePieceType { get; set; }
        public string EstateSeprationPiecesFloor { get;set; }
        public string EstateSeprationPiecesDirection { get; set; }
        public string EstateSeprationPiecesNorthLimit { get; set; }
        public string EstateSeprationPiecesWesternLimit { get; set; }
        public string EstateSeprationPiecesEasternLimit { get; set; }
        public string EstateSeprationPiecesSouthLimit { get; set; }
        public string EstateSeprationPiecesCommons { get; set; }
        public string EstateSeprationPiecesRights { get; set; }
        public string EstateSeprationPiecesDescription { get; set; }
        public string EstateSeprationPiecesUnitId { get; set; }
        public string EstateSeprationPieceSectionTitle { get; set; }
        public string EstateSeprationPieceSubSectionTitle { get; set; }
        public string EstateSeprationPieceSecondaryPlaque { get; set; }
        public string EstateSeprationPieceBasicPlaque { get; set; }
        public string EstateSeprationPieceDividedFromSecondaryPlaque { get; set; }
        public string EstateSeprationPiecePlaqueText { get; set; }
        public string EstateSeprationPieceKindId { get; set; }
        public string EstateSeprationPersonId { get; set; }
        public string EstateSeprationPieceDetailQuota { get; set; }
        public string EstateSeprationPieceTotalQuota { get; set; }
        public string RelatedDocumentNo {  get; set; }
        public string EstateRowNo { get; set; }
        public string EstateOwnershipDocumentType { get; set; }
        public string EstateOwnershipDocumentEloctronicPageNo { get; set; }
        public string EstateOwnershipDocumentIsReplacment { get; set; }
        public string EstateDocumentType { get; set; }
        public string EstateOwnershipSabtNo { get; set; }
        public string EstateOwnershipDocNo { get; set; }
        public string EstateOwnershipBookNo { get; set; }
        public string EstateOwnershipBookPageNo { get; set; }
        public string EstateOwnershipSardaftar { get; set; }
        public string EstateOwnershipBooktype { get; set; }
        public string EstateOwnershipSabtStateReportNo { get; set; }
        public string EstateOwnershipSabtStateReportDate { get; set; }
        public string EstateOwnershipSabtStateReportUnitName { get; set; }
        public string EstateOwnershipNotaryNo { get; set; }
        public string EstateOwnershipNotaryLocation { get; set; }
        public string EstateOwnershipNotaryDocumentNo { get; set; }
        public string EstateOwnershipNotaryDocumentDate { get; set; }
        public string EstateOwnershipDescription { get; set; }
        public string InquiryReplyDate { get; set; }
        public string InquiryReplyNo { get; set; }
        public string InquiryDescription { get; set; }
        public string InquiryOrganizationTitle { get; set; }
    }
}
