
using Notary.SSAA.BO.Domain.Entities;
namespace Notary.SSAA.BO.WebApi.Seeds.SignRequest.Entities.SignRequestCollection
{
    public class StaticSignRequestCollection
    {
        public List<Domain.Entities.SignRequest> GenerateSignRequests()
        {
            var requests = new List<Domain.Entities.SignRequest>();

            // --------- REQUEST 1 ----------
            var sr1Id = Guid.Parse("62f720b6-c03b-4dfd-908e-cff35e8c6bed");
            var sr1PersonIds = new List<Guid> { Guid.Parse("e731dbde-b900-4bcc-ae6d-3cfff332aa30"), Guid.Parse("870ec471-7e8e-4d50-a53e-b9855471750f"), Guid.Parse("f98ddfac-81fc-431a-b9ae-8f1e8be58e40") };
            var sr1 = new Domain.Entities.SignRequest
            {
                Id = sr1Id,
                ReqNo = "140444457999000001",
                ReqDate = "1404/01/01",
                ReqTime = "10:00:00",
                ScriptoriumId = "57999",
                SignRequestGetterId = "01",
                SignRequestSubjectId = "0101",
                IsCostPaid = "1",
                SumPrices = 35000,
                ReceiptNo = "1234567891",
                PayCostDate = "1404/01/01",
                PayCostTime = "10:00:00",
                PaymentType = "PCPOS",
                BillNo = "1404010112345671",
                NationalNo = "140402157999000001",
                SecretCode = "123456",
                SignDate = "1404/01/01",
                SignTime = "10:00:00",
                Modifier = "زهرا رضایی",
                ModifyDate = "1404/01/01",
                ModifyTime = "10:00:00",
                Confirmer = "فاطمه محمدی",
                ConfirmDate = "1404/01/01",
                ConfirmTime = "10:00:00",
                DigitalSign = "StaticBase64String",
                SignCertificateDn = "CN=SampleCertificate-1234,O=Notary,OU=SSAA",
                IsRemoteRequest = "2",
                State = "2",
                Ilm = "1",
                RecordDate = DateTime.MaxValue,
                IsReadyToPay = "1",
                LegacyId = $"LEGACY_{sr1Id.ToString().Substring(0, 8).ToUpper()}",
                SignText = "امضا انجام شد",
                SignRequestPeople = new List<SignRequestPerson>
            {
                new SignRequestPerson
                {
                    Id = sr1PersonIds[0],
                    SignRequestId = sr1Id,
                    RowNo = 1,
                    SignClassifyNo = 72875,
                    IsOriginal = "1",
                    IsRelated = "2",
                    PersonType = "1",
                    IsIranian = "1",
                    NationalNo = "1234567890",
                    Name = "محمد",
                    Family = "محمدی",
                    BirthDate = "1360/01/01",
                    SexType = "2",
                    FatherName = "حسن",
                    IdentityIssueLocation = "تهران",
                    IdentityNo = "1000001",
                    SeriAlpha = "1",
                    Seri = "10",
                    Serial = "500001",
                    SanaState = "1",
                    MobileNoState = "1",
                    IsSabtahvalChecked = "1",
                    IsSabtahvalCorrect = "1",
                    IsAlive = "1",
                    TfaState = "1",
                    IsFingerprintGotten = "1",
                    MobileNo = "09123456780",
                    PostalCode = "1234567890",
                    Address = "آدرس نمونه در شهر تهران",
                    Description = "",
                    ScriptoriumId = "57999",
                    Ilm = "1",
                    RecordDate = DateTime.MaxValue,
                    SignClassifyNoDescription = "شماره ترتیب اصلی"
                },
                new SignRequestPerson
                {
                    Id = sr1PersonIds[1],
                    SignRequestId = sr1Id,
                    RowNo = 2,
                    SignClassifyNo = 72876,
                    IsOriginal = "2",
                    IsRelated = "1",
                    PersonType = "1",
                    IsIranian = "1",
                    NationalNo = "1234567891",
                    Name = "زهرا",
                    Family = "رضایی",
                    BirthDate = "1362/01/01",
                    SexType = "1",
                    FatherName = "علی",
                    IdentityIssueLocation = "مشهد",
                    IdentityNo = "2000001",
                    SeriAlpha = "2",
                    Seri = "20",
                    Serial = "500002",
                    SanaState = "1",
                    MobileNoState = "1",
                    IsSabtahvalChecked = "1",
                    IsSabtahvalCorrect = "1",
                    IsAlive = "1",
                    TfaState = "1",
                    IsFingerprintGotten = "1",
                    MobileNo = "09123456781",
                    PostalCode = "1234567891",
                    Address = "آدرس نمونه در شهر مشهد",
                    Description = "",
                    ScriptoriumId = "57999",
                    Ilm = "1",
                    RecordDate = DateTime.MaxValue,
                    SignClassifyNoDescription = "شماره ترتیب وابسته"
                },
                new SignRequestPerson
                {
                    Id = sr1PersonIds[2],
                    SignRequestId = sr1Id,
                    RowNo = 3,
                    SignClassifyNo = 72877,
                    IsOriginal = "1",
                    IsRelated = "2",
                    PersonType = "1",
                    IsIranian = "1",
                    NationalNo = "1234567892",
                    Name = "مریم",
                    Family = "جعفری",
                    BirthDate = "1365/01/01",
                    SexType = "1",
                    FatherName = "رضا",
                    IdentityIssueLocation = "اصفهان",
                    IdentityNo = "3000001",
                    SeriAlpha = "2",
                    Seri = "30",
                    Serial = "500003",
                    SanaState = "1",
                    MobileNoState = "1",
                    IsSabtahvalChecked = "1",
                    IsSabtahvalCorrect = "1",
                    IsAlive = "1",
                    TfaState = "1",
                    IsFingerprintGotten = "1",
                    MobileNo = "09123456782",
                    PostalCode = "1234567892",
                    Address = "آدرس نمونه در شهر اصفهان",
                    Description = "",
                    ScriptoriumId = "57999",
                    Ilm = "1",
                    RecordDate = DateTime.MaxValue,
                    SignClassifyNoDescription = "شماره ترتیب وابسته"
                }
            },
                SignRequestPersonRelateds = new List<SignRequestPersonRelated>
            {
                new SignRequestPersonRelated
                {
                    Id = Guid.Parse("6fc3ac49-5dc3-4dc2-8cd7-39e1a48a7dbd"),
                    SignRequestId = sr1Id,
                    RowNo = 1,
                    MainPersonId = sr1PersonIds[0],
                    AgentPersonId = sr1PersonIds[1],
                    AgentTypeId = "1",
                    IsAgentDocumentAbroad = "2",
                    IsRelatedDocumentInSsar = "1",
                    AgentDocumentNo = "1234",
                    AgentDocumentDate = "1404/01/01",
                    AgentDocumentIssuer = "تهران",
                    SignRequestScriptoriumId = "57999",
                    Ilm = "1",
                    RecordDate = DateTime.MaxValue,
                    Description = "رابطه وکالت تنظیم شده"
                }
            },
                SignElectronicBooks = new List<SignElectronicBook>
            {
                new SignElectronicBook
                {
                    Id = Guid.Parse("0824ba77-86a2-4380-9450-e2ecb182710d"),
                    ScriptoriumId = "57999",
                    ClassifyNo = 72875,
                    SignRequestId = sr1Id,
                    SignRequestNationalNo = "1234567890",
                    SignRequestPersonId = sr1PersonIds[0],
                    SignDate = "1404/01/01",
                    HashOfFingerprint = "StaticBase64String44",
                    HashOfFile = "StaticBase64String44",
                    DigitalSign = "StaticBase64String200",
                    ConfirmDate = "1404/01/01",
                    ConfirmTime = "10:00:00",
                    RecordDate = DateTime.MaxValue,
                    Ilm = "1",
                    SignCertificateDn = "CN=SampleCertificate-1234,O=Notary,OU=SSAA"
                }
            }
            };
            requests.Add(sr1);

            // --------- REQUEST 2 ----------
            var sr2Id = Guid.Parse("0a190675-b674-46d3-8ad6-33736ff33bdc");
            var sr2PersonIds = new List<Guid> { Guid.Parse("6f7c40c4-6b54-49e8-8d8e-742dd205924a"), Guid.Parse("4191a952-36a7-4880-bc17-07c72037a239"), Guid.Parse("22dfd2cb-762b-490b-b28a-2bbc4cb2a52a") };
            var sr2 = new Domain.Entities.SignRequest
            {
                Id = sr2Id,
                ReqNo = "140444457999000002",
                ReqDate = "1404/01/02",
                ReqTime = "11:00:00",
                ScriptoriumId = "57999",
                SignRequestGetterId = "02",
                SignRequestSubjectId = "0101",
                IsCostPaid = "1",
                SumPrices = 36000,
                ReceiptNo = "1234567892",
                PayCostDate = "1404/01/02",
                PayCostTime = "11:00:00",
                PaymentType = "PCPOS",
                BillNo = "1404010112345672",
                NationalNo = "140402157999000002",
                SecretCode = "234567",
                SignDate = "1404/01/02",
                SignTime = "11:00:00",
                Modifier = "سارا حسینی",
                ModifyDate = "1404/01/02",
                ModifyTime = "11:00:00",
                Confirmer = "مینا کریمی",
                ConfirmDate = "1404/01/02",
                ConfirmTime = "11:00:00",
                DigitalSign = "StaticBase64String2",
                SignCertificateDn = "CN=SampleCertificate-1235,O=Notary,OU=SSAA",
                IsRemoteRequest = "2",
                State = "1",
                Ilm = "1",
                RecordDate = DateTime.MaxValue,
                IsReadyToPay = "1",
                LegacyId = $"LEGACY_{sr2Id.ToString().Substring(0, 8).ToUpper()}",
                SignText = "امضا انجام شد",
                SignRequestPeople = new List<SignRequestPerson>
            {
                new SignRequestPerson
                {
                    Id = sr2PersonIds[0],
                    SignRequestId = sr2Id,
                    RowNo = 1,
                    SignClassifyNo = 72876,
                    IsOriginal = "1",
                    IsRelated = "2",
                    PersonType = "1",
                    IsIranian = "1",
                    NationalNo = "2234567890",
                    Name = "رضا",
                    Family = "رحمانی",
                    BirthDate = "1361/01/01",
                    SexType = "2",
                    FatherName = "محمد",
                    IdentityIssueLocation = "شیراز",
                    IdentityNo = "1000002",
                    SeriAlpha = "1",
                    Seri = "11",
                    Serial = "500002",
                    SanaState = "1",
                    MobileNoState = "1",
                    IsSabtahvalChecked = "1",
                    IsSabtahvalCorrect = "1",
                    IsAlive = "1",
                    TfaState = "1",
                    IsFingerprintGotten = "1",
                    MobileNo = "09123456783",
                    PostalCode = "2234567890",
                    Address = "آدرس نمونه در شهر شیراز",
                    Description = "",
                    ScriptoriumId = "57999",
                    Ilm = "1",
                    RecordDate = DateTime.MaxValue,
                    SignClassifyNoDescription = "شماره ترتیب اصلی"
                },
                new SignRequestPerson
                {
                    Id = sr2PersonIds[1],
                    SignRequestId = sr2Id,
                    RowNo = 2,
                    SignClassifyNo = 72877,
                    IsOriginal = "2",
                    IsRelated = "1",
                    PersonType = "1",
                    IsIranian = "1",
                    NationalNo = "2234567891",
                    Name = "نرگس",
                    Family = "موسوی",
                    BirthDate = "1363/01/01",
                    SexType = "1",
                    FatherName = "حسین",
                    IdentityIssueLocation = "تبریز",
                    IdentityNo = "2000002",
                    SeriAlpha = "2",
                    Seri = "21",
                    Serial = "500003",
                    SanaState = "1",
                    MobileNoState = "1",
                    IsSabtahvalChecked = "1",
                    IsSabtahvalCorrect = "1",
                    IsAlive = "1",
                    TfaState = "1",
                    IsFingerprintGotten = "1",
                    MobileNo = "09123456784",
                    PostalCode = "2234567891",
                    Address = "آدرس نمونه در شهر تبریز",
                    Description = "",
                    ScriptoriumId = "57999",
                    Ilm = "1",
                    RecordDate = DateTime.MaxValue,
                    SignClassifyNoDescription = "شماره ترتیب وابسته"
                },
                new SignRequestPerson
                {
                    Id = sr2PersonIds[2],
                    SignRequestId = sr2Id,
                    RowNo = 3,
                    SignClassifyNo = 72878,
                    IsOriginal = "2",
                    IsRelated = "1",
                    PersonType = "1",
                    IsIranian = "1",
                    NationalNo = "2234567892",
                    Name = "لیلا",
                    Family = "قاسمی",
                    BirthDate = "1366/01/01",
                    SexType = "1",
                    FatherName = "احمد",
                    IdentityIssueLocation = "رشت",
                    IdentityNo = "3000002",
                    SeriAlpha = "2",
                    Seri = "31",
                    Serial = "500004",
                    SanaState = "1",
                    MobileNoState = "1",
                    IsSabtahvalChecked = "1",
                    IsSabtahvalCorrect = "1",
                    IsAlive = "1",
                    TfaState = "1",
                    IsFingerprintGotten = "1",
                    MobileNo = "09123456785",
                    PostalCode = "2234567892",
                    Address = "آدرس نمونه در شهر رشت",
                    Description = "",
                    ScriptoriumId = "57999",
                    Ilm = "1",
                    RecordDate = DateTime.MaxValue,
                    SignClassifyNoDescription = "شماره ترتیب وابسته"
                }
            },
                SignRequestPersonRelateds = new List<SignRequestPersonRelated>
            {
                new SignRequestPersonRelated
                {
                    Id = Guid.Parse("a86272fc-2dcb-480d-98ac-a9793ff59022"),
                    SignRequestId = sr2Id,
                    RowNo = 1,
                    MainPersonId = sr2PersonIds[0],
                    AgentPersonId = sr2PersonIds[1],
                    AgentTypeId = "1",
                    IsAgentDocumentAbroad = "2",
                    IsRelatedDocumentInSsar = "1",
                    AgentDocumentNo = "2234",
                    AgentDocumentDate = "1404/01/02",
                    AgentDocumentIssuer = "شیراز",
                    SignRequestScriptoriumId = "57999",
                    Ilm = "1",
                    RecordDate = DateTime.MaxValue,
                    Description = "رابطه وکالت تنظیم شده"
                },
                new SignRequestPersonRelated
                {
                    Id = Guid.Parse("64028e98-802a-4c37-aafe-27c3aa418fde"),
                    SignRequestId = sr2Id,
                    RowNo = 2,
                    MainPersonId = sr2PersonIds[0],
                    AgentPersonId = sr2PersonIds[2],
                    AgentTypeId = "2",
                    IsAgentDocumentAbroad = "2",
                    IsRelatedDocumentInSsar = "1",
                    AgentDocumentNo = "2235",
                    AgentDocumentDate = "1404/01/02",
                    AgentDocumentIssuer = "تبریز",
                    SignRequestScriptoriumId = "57999",
                    Ilm = "1",
                    RecordDate = DateTime.MaxValue,
                    Description = "رابطه وکالت تنظیم شده"
                }
            },
                SignElectronicBooks = new List<SignElectronicBook>
            {
                new SignElectronicBook
                {
                    Id = Guid.Parse("34e4c049-1d53-4bd5-a0de-82e700b11c46"),
                    ScriptoriumId = "57999",
                    ClassifyNo = 72876,
                    SignRequestId = sr2Id,
                    SignRequestNationalNo = "2234567890",
                    SignRequestPersonId = sr2PersonIds[0],
                    SignDate = "1404/01/02",
                    HashOfFingerprint = "StaticBase64String45",
                    HashOfFile = "StaticBase64String45",
                    DigitalSign = "StaticBase64String201",
                    ConfirmDate = "1404/01/02",
                    ConfirmTime = "11:00:00",
                    RecordDate = DateTime.MaxValue,
                    Ilm = "1",
                    SignCertificateDn = "CN=SampleCertificate-1235,O=Notary,OU=SSAA"
                }
            }
            };
            requests.Add(sr2);

            // --------- REQUEST 3 ----------
            var sr3Id = Guid.Parse("7050d603-d96e-452f-9277-13ba0afb8000");
            var sr3PersonIds = new List<Guid> { Guid.Parse("3b917530-1f05-4e0e-8d71-77fd05126758"), Guid.Parse("44a83e67-1c90-43de-b703-637429625974"), Guid.Parse("9116cbc1-423f-4825-b48a-68f81744dafc") };
            var sr3 = new Domain.Entities.SignRequest
            {
                Id = sr3Id,
                ReqNo = "140444457999000003",
                ReqDate = "1404/01/03",
                ReqTime = "12:00:00",
                ScriptoriumId = "57999",
                SignRequestGetterId = "03",
                SignRequestSubjectId = "0102",
                IsCostPaid = "2",
                SumPrices = 0,
                ReceiptNo = "",
                PayCostDate = "",
                PayCostTime = "",
                PaymentType = "",
                BillNo = "",
                NationalNo = "",
                SecretCode = "",
                SignDate = "",
                SignTime = "",
                Modifier = "",
                ModifyDate = "",
                ModifyTime = "",
                Confirmer = "",
                ConfirmDate = "",
                ConfirmTime = "",
                DigitalSign = "",
                SignCertificateDn = "",
                IsRemoteRequest = "2",
                State = "1",
                Ilm = "1",
                RecordDate = DateTime.MaxValue,
                IsReadyToPay = "1",
                LegacyId = $"LEGACY_{sr3Id.ToString().Substring(0, 8).ToUpper()}",
                SignText = "امضا انجام شد",
                SignRequestPeople = new List<SignRequestPerson>
            {
                new SignRequestPerson
                {
                    Id = sr3PersonIds[0],
                    SignRequestId = sr3Id,
                    RowNo = 1,
                    SignClassifyNo = 72877,
                    IsOriginal = "1",
                    IsRelated = "2",
                    PersonType = "1",
                    IsIranian = "1",
                    NationalNo = "3234567890",
                    Name = "امیر",
                    Family = "کاظمی",
                    BirthDate = "1362/01/01",
                    SexType = "2",
                    FatherName = "مهدی",
                    IdentityIssueLocation = "اهواز",
                    IdentityNo = "1000003",
                    SeriAlpha = "1",
                    Seri = "12",
                    Serial = "500003",
                    SanaState = "1",
                    MobileNoState = "1",
                    IsSabtahvalChecked = "1",
                    IsSabtahvalCorrect = "1",
                    IsAlive = "1",
                    TfaState = "1",
                    IsFingerprintGotten = "1",
                    MobileNo = "09123456786",
                    PostalCode = "3234567890",
                    Address = "آدرس نمونه در شهر اهواز",
                    Description = "",
                    ScriptoriumId = "57999",
                    Ilm = "1",
                    RecordDate = DateTime.MaxValue,
                    SignClassifyNoDescription = "شماره ترتیب اصلی"
                },
                new SignRequestPerson
                {
                    Id = sr3PersonIds[1],
                    SignRequestId = sr3Id,
                    RowNo = 2,
                    SignClassifyNo = 72878,
                    IsOriginal = "2",
                    IsRelated = "1",
                    PersonType = "1",
                    IsIranian = "1",
                    NationalNo = "3234567891",
                    Name = "فریبا",
                    Family = "نوری",
                    BirthDate = "1364/01/01",
                    SexType = "1",
                    FatherName = "کریم",
                    IdentityIssueLocation = "قم",
                    IdentityNo = "2000003",
                    SeriAlpha = "2",
                    Seri = "22",
                    Serial = "500004",
                    SanaState = "1",
                    MobileNoState = "1",
                    IsSabtahvalChecked = "1",
                    IsSabtahvalCorrect = "1",
                    IsAlive = "1",
                    TfaState = "1",
                    IsFingerprintGotten = "1",
                    MobileNo = "09123456787",
                    PostalCode = "3234567891",
                    Address = "آدرس نمونه در شهر قم",
                    Description = "",
                    ScriptoriumId = "57999",
                    Ilm = "1",
                    RecordDate = DateTime.MaxValue,
                    SignClassifyNoDescription = "شماره ترتیب وابسته"
                },
                new SignRequestPerson
                {
                    Id = sr3PersonIds[2],
                    SignRequestId = sr3Id,
                    RowNo = 3,
                    SignClassifyNo = 72879,
                    IsOriginal = "2",
                    IsRelated = "1",
                    PersonType = "1",
                    IsIranian = "1",
                    NationalNo = "3234567892",
                    Name = "نگار",
                    Family = "سلیمانی",
                    BirthDate = "1367/01/01",
                    SexType = "1",
                    FatherName = "مجید",
                    IdentityIssueLocation = "کرج",
                    IdentityNo = "3000003",
                    SeriAlpha = "2",
                    Seri = "32",
                    Serial = "500005",
                    SanaState = "1",
                    MobileNoState = "1",
                    IsSabtahvalChecked = "1",
                    IsSabtahvalCorrect = "1",
                    IsAlive = "1",
                    TfaState = "1",
                    IsFingerprintGotten = "1",
                    MobileNo = "09123456788",
                    PostalCode = "3234567892",
                    Address = "آدرس نمونه در شهر کرج",
                    Description = "",
                    ScriptoriumId = "57999",
                    Ilm = "1",
                    RecordDate = DateTime.MaxValue,
                    SignClassifyNoDescription = "شماره ترتیب وابسته"
                }
            },
                SignRequestPersonRelateds = new List<SignRequestPersonRelated>
            {
              
            },
                SignElectronicBooks = new List<SignElectronicBook>
            {

            }
            };
            requests.Add(sr3);

            // --------- REQUEST 4 ----------
            var sr4Id = Guid.Parse("597e2af5-43bc-40bc-83ec-6d233f04df26");
            var sr4PersonIds = new List<Guid> { Guid.Parse("840e93b0-95dc-4ebd-8b86-fd1c58b5d0ab"), Guid.Parse("e48e7011-2d22-4130-baeb-ca3e919efc18"), Guid.Parse("b16e2ae4-c915-4b01-8da0-e8a25e1ad997") };
            var sr4 = new Domain.Entities.SignRequest
            {
                Id = sr4Id,
                ReqNo = "140444457999000004",
                ReqDate = "1404/01/04",
                ReqTime = "13:00:00",
                ScriptoriumId = "57999",
                SignRequestGetterId = "04",
                SignRequestSubjectId = "0103",
                IsCostPaid = "1",
                SumPrices = 38000,
                ReceiptNo = "1234567894",
                PayCostDate = "1404/01/04",
                PayCostTime = "13:00:00",
                PaymentType = "PCPOS",
                BillNo = "1404010112345674",
                NationalNo = "140402157999000004",
                SecretCode = "456789",
                SignDate = "1404/01/04",
                SignTime = "13:00:00",
                Modifier = "نازنین رحیمی",
                ModifyDate = "1404/01/04",
                ModifyTime = "13:00:00",
                Confirmer = "الهه محمودی",
                ConfirmDate = "1404/01/04",
                ConfirmTime = "13:00:00",
                DigitalSign = "StaticBase64String4",
                SignCertificateDn = "CN=SampleCertificate-1237,O=Notary,OU=SSAA",
                IsRemoteRequest = "1",
                State = "2",
                Ilm = "1",
                RecordDate = DateTime.MaxValue,
                IsReadyToPay = "1",
                LegacyId = $"LEGACY_{sr4Id.ToString().Substring(0, 8).ToUpper()}",
                SignText = "امضا انجام شد",
                SignRequestPeople = new List<SignRequestPerson>
            {
                new SignRequestPerson
                {
                    Id = sr4PersonIds[0],
                    SignRequestId = sr4Id,
                    RowNo = 1,
                    SignClassifyNo = 72878,
                    IsOriginal = "1",
                    IsRelated = "2",
                    PersonType = "1",
                    IsIranian = "1",
                    NationalNo = "4234567890",
                    Name = "حسین",
                    Family = "مهدوی",
                    BirthDate = "1363/01/01",
                    SexType = "2",
                    FatherName = "عباس",
                    IdentityIssueLocation = "یزد",
                    IdentityNo = "1000004",
                    SeriAlpha = "1",
                    Seri = "13",
                    Serial = "500004",
                    SanaState = "1",
                    MobileNoState = "1",
                    IsSabtahvalChecked = "1",
                    IsSabtahvalCorrect = "1",
                    IsAlive = "1",
                    TfaState = "1",
                    IsFingerprintGotten = "1",
                    MobileNo = "09123456789",
                    PostalCode = "4234567890",
                    Address = "آدرس نمونه در شهر یزد",
                    Description = "",
                    ScriptoriumId = "57999",
                    Ilm = "1",
                    RecordDate = DateTime.MaxValue,
                    SignClassifyNoDescription = "شماره ترتیب اصلی"
                },
                new SignRequestPerson
                {
                    Id = sr4PersonIds[1],
                    SignRequestId = sr4Id,
                    RowNo = 2,
                    SignClassifyNo = 72879,
                    IsOriginal = "2",
                    IsRelated = "1",
                    PersonType = "1",
                    IsIranian = "1",
                    NationalNo = "4234567891",
                    Name = "سمیه",
                    Family = "حسینی",
                    BirthDate = "1365/01/01",
                    SexType = "1",
                    FatherName = "رضا",
                    IdentityIssueLocation = "ارومیه",
                    IdentityNo = "2000004",
                    SeriAlpha = "2",
                    Seri = "23",
                    Serial = "500005",
                    SanaState = "1",
                    MobileNoState = "1",
                    IsSabtahvalChecked = "1",
                    IsSabtahvalCorrect = "1",
                    IsAlive = "1",
                    TfaState = "1",
                    IsFingerprintGotten = "1",
                    MobileNo = "09123456790",
                    PostalCode = "4234567891",
                    Address = "آدرس نمونه در شهر ارومیه",
                    Description = "",
                    ScriptoriumId = "57999",
                    Ilm = "1",
                    RecordDate = DateTime.MaxValue,
                    SignClassifyNoDescription = "شماره ترتیب وابسته"
                },
                new SignRequestPerson
                {
                    Id = sr4PersonIds[2],
                    SignRequestId = sr4Id,
                    RowNo = 3,
                    SignClassifyNo = 72880,
                    IsOriginal = "2",
                    IsRelated = "1",
                    PersonType = "1",
                    IsIranian = "1",
                    NationalNo = "4234567892",
                    Name = "مرضیه",
                    Family = "امیری",
                    BirthDate = "1368/01/01",
                    SexType = "1",
                    FatherName = "محسن",
                    IdentityIssueLocation = "بندرعباس",
                    IdentityNo = "3000004",
                    SeriAlpha = "2",
                    Seri = "33",
                    Serial = "500006",
                    SanaState = "1",
                    MobileNoState = "1",
                    IsSabtahvalChecked = "1",
                    IsSabtahvalCorrect = "1",
                    IsAlive = "1",
                    TfaState = "1",
                    IsFingerprintGotten = "1",
                    MobileNo = "09123456791",
                    PostalCode = "4234567892",
                    Address = "آدرس نمونه در شهر بندرعباس",
                    Description = "",
                    ScriptoriumId = "57999",
                    Ilm = "1",
                    RecordDate = DateTime.MaxValue,
                    SignClassifyNoDescription = "شماره ترتیب وابسته"
                }
            },
                SignRequestPersonRelateds = new List<SignRequestPersonRelated>
            {
                new SignRequestPersonRelated
                {
                    Id = Guid.Parse("f88d75cd-9d7c-4867-9285-c9cb2361d998"),
                    SignRequestId = sr4Id,
                    RowNo = 1,
                    MainPersonId = sr4PersonIds[0],
                    AgentPersonId = sr4PersonIds[1],
                    AgentTypeId = "0",
                    IsAgentDocumentAbroad = "2",
                    IsRelatedDocumentInSsar = "1",
                    AgentDocumentNo = "4234",
                    AgentDocumentDate = "1404/01/04",
                    AgentDocumentIssuer = "یزد",
                    SignRequestScriptoriumId = "57999",
                    Ilm = "1",
                    RecordDate = DateTime.MaxValue,
                    Description = "رابطه وکالت تنظیم شده"
                },
                new SignRequestPersonRelated
                {
                    Id = Guid.Parse("705ea36e-4c71-4f2e-a665-c8be760d48bc"),
                    SignRequestId = sr4Id,
                    RowNo = 2,
                    MainPersonId = sr4PersonIds[0],
                    AgentPersonId = sr4PersonIds[2],
                    AgentTypeId = "2",
                    IsAgentDocumentAbroad = "2",
                    IsRelatedDocumentInSsar = "1",
                    AgentDocumentNo = "4235",
                    AgentDocumentDate = "1404/01/04",
                    AgentDocumentIssuer = "ارومیه",
                    SignRequestScriptoriumId = "57999",
                    Ilm = "1",
                    RecordDate = DateTime.MaxValue,
                    Description = "رابطه وکالت تنظیم شده"
                }
            },
                SignElectronicBooks = new List<SignElectronicBook>
            {
                new SignElectronicBook
                {
                    Id = Guid.Parse("dd14dfaa-9cd6-4891-9e05-86b493f3afea"),
                    ScriptoriumId = "57999",
                    ClassifyNo = 72878,
                    SignRequestId = sr4Id,
                    SignRequestNationalNo = "4234567890",
                    SignRequestPersonId = sr4PersonIds[0],
                    SignDate = "1404/01/04",
                    HashOfFingerprint = "StaticBase64String47",
                    HashOfFile = "StaticBase64String47",
                    DigitalSign = "StaticBase64String203",
                    ConfirmDate = "1404/01/04",
                    ConfirmTime = "13:00:00",
                    RecordDate = DateTime.MaxValue,
                    Ilm = "1",
                    SignCertificateDn = "CN=SampleCertificate-1237,O=Notary,OU=SSAA"
                }
            }
            };
            requests.Add(sr4);

            // --------- REQUEST 5 ----------
            var sr5Id = Guid.Parse("40af6b8a-def6-41bc-ac53-326b54f6cb0c");
            var sr5PersonIds = new List<Guid> { Guid.Parse("299b48a8-fa42-47fc-ab9a-59305cb6c6b9"), Guid.Parse("dc2039ae-499f-4607-8294-d25a2fd4caf2"), Guid.Parse("4f93497c-e3af-449a-acb7-07851dd58518") };
            var sr5 = new Domain.Entities.SignRequest
            {
                Id = sr5Id,
                ReqNo = "140444457999000005",
                ReqDate = "1404/01/05",
                ReqTime = "14:00:00",
                ScriptoriumId = "57999",
                SignRequestGetterId = "05",
                SignRequestSubjectId = "0104",
                IsCostPaid = "1",
                SumPrices = 39000,
                ReceiptNo = "1234567895",
                PayCostDate = "1404/01/05",
                PayCostTime = "14:00:00",
                PaymentType = "PCPOS",
                BillNo = "1404010112345675",
                NationalNo = "140402157999000005",
                SecretCode = "567890",
                SignDate = "1404/01/05",
                SignTime = "14:00:00",
                Modifier = "الهام صادقی",
                ModifyDate = "1404/01/05",
                ModifyTime = "14:00:00",
                Confirmer = "شیرین محمدی",
                ConfirmDate = "1404/01/05",
                ConfirmTime = "14:00:00",
                DigitalSign = "StaticBase64String5",
                SignCertificateDn = "CN=SampleCertificate-1238,O=Notary,OU=SSAA",
                IsRemoteRequest = "1",
                State = "2",
                Ilm = "1",
                RecordDate = DateTime.MaxValue,
                IsReadyToPay = "1",
                LegacyId = $"LEGACY_{sr5Id.ToString().Substring(0, 8).ToUpper()}",
                SignText = "امضا انجام شد",
                SignRequestPeople = new List<SignRequestPerson>
            {
                new SignRequestPerson
                {
                    Id = sr5PersonIds[0],
                    SignRequestId = sr5Id,
                    RowNo = 1,
                    SignClassifyNo = 72879,
                    IsOriginal = "1",
                    IsRelated = "2",
                    PersonType = "1",
                    IsIranian = "1",
                    NationalNo = "5234567890",
                    Name = "مجید",
                    Family = "جعفری",
                    BirthDate = "1364/01/01",
                    SexType = "2",
                    FatherName = "حسین",
                    IdentityIssueLocation = "کرمان",
                    IdentityNo = "1000005",
                    SeriAlpha = "1",
                    Seri = "14",
                    Serial = "500005",
                    SanaState = "1",
                    MobileNoState = "1",
                    IsSabtahvalChecked = "1",
                    IsSabtahvalCorrect = "1",
                    IsAlive = "1",
                    TfaState = "1",
                    IsFingerprintGotten = "1",
                    MobileNo = "09123456792",
                    PostalCode = "5234567890",
                    Address = "آدرس نمونه در شهر کرمان",
                    Description = "",
                    ScriptoriumId = "57999",
                    Ilm = "1",
                    RecordDate = DateTime.MaxValue,
                    SignClassifyNoDescription = "شماره ترتیب اصلی"
                },
                new SignRequestPerson
                {
                    Id = sr5PersonIds[1],
                    SignRequestId = sr5Id,
                    RowNo = 2,
                    SignClassifyNo = 72880,
                    IsOriginal = "2",
                    IsRelated = "1",
                    PersonType = "1",
                    IsIranian = "1",
                    NationalNo = "5234567891",
                    Name = "طاهره",
                    Family = "کریمی",
                    BirthDate = "1366/01/01",
                    SexType = "1",
                    FatherName = "محمود",
                    IdentityIssueLocation = "همدان",
                    IdentityNo = "2000005",
                    SeriAlpha = "2",
                    Seri = "24",
                    Serial = "500006",
                    SanaState = "1",
                    MobileNoState = "1",
                    IsSabtahvalChecked = "1",
                    IsSabtahvalCorrect = "1",
                    IsAlive = "1",
                    TfaState = "1",
                    IsFingerprintGotten = "1",
                    MobileNo = "09123456793",
                    PostalCode = "5234567891",
                    Address = "آدرس نمونه در شهر همدان",
                    Description = "",
                    ScriptoriumId = "57999",
                    Ilm = "1",
                    RecordDate = DateTime.MaxValue,
                    SignClassifyNoDescription = "شماره ترتیب وابسته"
                },
                new SignRequestPerson
                {
                    Id = sr5PersonIds[2],
                    SignRequestId = sr5Id,
                    RowNo = 3,
                    SignClassifyNo = 72881,
                    IsOriginal = "2",
                    IsRelated = "1",
                    PersonType = "1",
                    IsIranian = "1",
                    NationalNo = "5234567892",
                    Name = "زینب",
                    Family = "رحمانی",
                    BirthDate = "1369/01/01",
                    SexType = "1",
                    FatherName = "اکبر",
                    IdentityIssueLocation = "سنندج",
                    IdentityNo = "3000005",
                    SeriAlpha = "2",
                    Seri = "34",
                    Serial = "500007",
                    SanaState = "1",
                    MobileNoState = "1",
                    IsSabtahvalChecked = "1",
                    IsSabtahvalCorrect = "1",
                    IsAlive = "1",
                    TfaState = "1",
                    IsFingerprintGotten = "1",
                    MobileNo = "09123456794",
                    PostalCode = "5234567892",
                    Address = "آدرس نمونه در شهر سنندج",
                    Description = "",
                    ScriptoriumId = "57999",
                    Ilm = "1",
                    RecordDate = DateTime.MaxValue,
                    SignClassifyNoDescription = "شماره ترتیب وابسته"
                }
            },
                SignRequestPersonRelateds = new List<SignRequestPersonRelated>
            {
                new SignRequestPersonRelated
                {
                    Id = Guid.Parse("f1c0b65e-842f-4d25-87b5-8e762ebf1c43"),
                    SignRequestId = sr5Id,
                    RowNo = 1,
                    MainPersonId = sr5PersonIds[0],
                    AgentPersonId = sr5PersonIds[1],
                    AgentTypeId = "1",
                    IsAgentDocumentAbroad = "2",
                    IsRelatedDocumentInSsar = "1",
                    AgentDocumentNo = "5234",
                    AgentDocumentDate = "1404/01/05",
                    AgentDocumentIssuer = "کرمان",
                    SignRequestScriptoriumId = "57999",
                    Ilm = "1",
                    RecordDate = DateTime.MaxValue,
                    Description = "رابطه وکالت تنظیم شده"
                },
                new SignRequestPersonRelated
                {
                    Id = Guid.Parse("a0cec4c7-a31e-4139-ae1e-c1391da07748"),
                    SignRequestId = sr5Id,
                    RowNo = 2,
                    MainPersonId = sr5PersonIds[0],
                    AgentPersonId = sr5PersonIds[2],
                    AgentTypeId = "2",
                    IsAgentDocumentAbroad = "2",
                    IsRelatedDocumentInSsar = "1",
                    AgentDocumentNo = "5235",
                    AgentDocumentDate = "1404/01/05",
                    AgentDocumentIssuer = "همدان",
                    SignRequestScriptoriumId = "57999",
                    Ilm = "1",
                    RecordDate = DateTime.MaxValue,
                    Description = "رابطه وکالت تنظیم شده"
                }
            },
                SignElectronicBooks = new List<SignElectronicBook>
            {
                new SignElectronicBook
                {
                    Id = Guid.Parse("b3e7f505-c24a-4c4e-9fdb-7cb29956855b"),
                    ScriptoriumId = "57999",
                    ClassifyNo = 72879,
                    SignRequestId = sr5Id,
                    SignRequestNationalNo = "5234567890",
                    SignRequestPersonId = sr5PersonIds[0],
                    SignDate = "1404/01/05",
                    HashOfFingerprint = "StaticBase64String48",
                    HashOfFile = "StaticBase64String48",
                    DigitalSign = "StaticBase64String204",
                    ConfirmDate = "1404/01/05",
                    ConfirmTime = "14:00:00",
                    RecordDate = DateTime.MaxValue,
                    Ilm = "1",
                    SignCertificateDn = "CN=SampleCertificate-1238,O=Notary,OU=SSAA"
                }
            }
            };
            requests.Add(sr5);

            // --------- REQUEST 6 ----------
            var sr6Id = Guid.Parse("2008281d-a894-4e03-bdc2-ed60bcaad69d");
            var sr6PersonIds = new List<Guid> { Guid.Parse("344e6fd9-bfd8-4194-b6fc-c5a5f51690eb"), Guid.Parse("93aae3fd-79ae-4e48-8652-79c799256c46"), Guid.Parse("73360bf3-7572-4ade-80a3-4b619e93c1e4") };
            var sr6 = new Domain.Entities.SignRequest
            {
                Id = sr6Id,
                ReqNo = "140444452539000001",
                ReqDate = "1404/01/06",
                ReqTime = "15:00:00",
                ScriptoriumId = "52539",
                SignRequestGetterId = "04",
                SignRequestSubjectId = "0105",
                IsCostPaid = "1",
                SumPrices = 40000,
                ReceiptNo = "1234567896",
                PayCostDate = "1404/01/06",
                PayCostTime = "15:00:00",
                PaymentType = "PCPOS",
                BillNo = "1404010112345676",
                NationalNo = "1404021525399000001",
                SecretCode = "678901",
                SignDate = "1404/01/06",
                SignTime = "15:00:00",
                Modifier = "مینا احمدی",
                ModifyDate = "1404/01/06",
                ModifyTime = "15:00:00",
                Confirmer = "نرگس رضایی",
                ConfirmDate = "1404/01/06",
                ConfirmTime = "15:00:00",
                DigitalSign = "StaticBase64String6",
                SignCertificateDn = "CN=SampleCertificate-1239,O=Notary,OU=SSAA",
                IsRemoteRequest = "1",
                State = "2",
                Ilm = "1",
                RecordDate = DateTime.MaxValue,
                IsReadyToPay = "1",
                LegacyId = $"LEGACY_{sr6Id.ToString().Substring(0, 8).ToUpper()}",
                SignText = "امضا انجام شد",
                SignRequestPeople = new List<SignRequestPerson>
            {
                new SignRequestPerson
                {
                    Id = sr6PersonIds[0],
                    SignRequestId = sr6Id,
                    RowNo = 1,
                    SignClassifyNo = 72880,
                    IsOriginal = "1",
                    IsRelated = "2",
                    PersonType = "1",
                    IsIranian = "1",
                    NationalNo = "6234567890",
                    Name = "سعید",
                    Family = "محمدی",
                    BirthDate = "1365/01/01",
                    SexType = "2",
                    FatherName = "علی",
                    IdentityIssueLocation = "زاهدان",
                    IdentityNo = "1000006",
                    SeriAlpha = "1",
                    Seri = "15",
                    Serial = "500006",
                    SanaState = "1",
                    MobileNoState = "1",
                    IsSabtahvalChecked = "1",
                    IsSabtahvalCorrect = "1",
                    IsAlive = "1",
                    TfaState = "1",
                    IsFingerprintGotten = "1",
                    MobileNo = "09123456795",
                    PostalCode = "6234567890",
                    Address = "آدرس نمونه در شهر زاهدان",
                    Description = "",
                    ScriptoriumId = "52539",
                    Ilm = "1",
                    RecordDate = DateTime.MaxValue,
                    SignClassifyNoDescription = "شماره ترتیب اصلی"
                },
                new SignRequestPerson
                {
                    Id = sr6PersonIds[1],
                    SignRequestId = sr6Id,
                    RowNo = 2,
                    SignClassifyNo = 72881,
                    IsOriginal = "2",
                    IsRelated = "1",
                    PersonType = "1",
                    IsIranian = "1",
                    NationalNo = "6234567891",
                    Name = "فاطمه",
                    Family = "حسنی",
                    BirthDate = "1367/01/01",
                    SexType = "1",
                    FatherName = "محمدرضا",
                    IdentityIssueLocation = "گرگان",
                    IdentityNo = "2000006",
                    SeriAlpha = "2",
                    Seri = "25",
                    Serial = "500007",
                    SanaState = "1",
                    MobileNoState = "1",
                    IsSabtahvalChecked = "1",
                    IsSabtahvalCorrect = "1",
                    IsAlive = "1",
                    TfaState = "1",
                    IsFingerprintGotten = "1",
                    MobileNo = "09123456796",
                    PostalCode = "6234567891",
                    Address = "آدرس نمونه در شهر گرگان",
                    Description = "",
                    ScriptoriumId = "52539",
                    Ilm = "1",
                    RecordDate = DateTime.MaxValue,
                    SignClassifyNoDescription = "شماره ترتیب وابسته"
                },
                new SignRequestPerson
                {
                    Id = sr6PersonIds[2],
                    SignRequestId = sr6Id,
                    RowNo = 3,
                    SignClassifyNo = 72882,
                    IsOriginal = "2",
                    IsRelated = "1",
                    PersonType = "1",
                    IsIranian = "1",
                    NationalNo = "6234567892",
                    Name = "لیلا",
                    Family = "موسوی",
                    BirthDate = "1370/01/01",
                    SexType = "1",
                    FatherName = "حیدر",
                    IdentityIssueLocation = "ساری",
                    IdentityNo = "3000006",
                    SeriAlpha = "2",
                    Seri = "35",
                    Serial = "500008",
                    SanaState = "1",
                    MobileNoState = "1",
                    IsSabtahvalChecked = "1",
                    IsSabtahvalCorrect = "1",
                    IsAlive = "1",
                    TfaState = "1",
                    IsFingerprintGotten = "1",
                    MobileNo = "09123456797",
                    PostalCode = "6234567892",
                    Address = "آدرس نمونه در شهر ساری",
                    Description = "",
                    ScriptoriumId = "52539",
                    Ilm = "1",
                    RecordDate = DateTime.MaxValue,
                    SignClassifyNoDescription = "شماره ترتیب وابسته"
                }
            },
                SignRequestPersonRelateds = new List<SignRequestPersonRelated>
            {
                new SignRequestPersonRelated
                {
                    Id = Guid.Parse("057e6962-f300-480d-8c8c-60fef31a1a8f"),
                    SignRequestId = sr6Id,
                    RowNo = 1,
                    MainPersonId = sr6PersonIds[0],
                    AgentPersonId = sr6PersonIds[1],
                    AgentTypeId = "1",
                    IsAgentDocumentAbroad = "2",
                    IsRelatedDocumentInSsar = "1",
                    AgentDocumentNo = "6234",
                    AgentDocumentDate = "1404/01/06",
                    AgentDocumentIssuer = "زاهدان",
                    SignRequestScriptoriumId = "52539",
                    Ilm = "1",
                    RecordDate = DateTime.MaxValue,
                    Description = "رابطه وکالت تنظیم شده"
                },
                new SignRequestPersonRelated
                {
                    Id = Guid.Parse("75eeea07-6ae5-4783-88a1-b12097c70414"),
                    SignRequestId = sr6Id,
                    RowNo = 2,
                    MainPersonId = sr6PersonIds[0],
                    AgentPersonId = sr6PersonIds[2],
                    AgentTypeId = "2",
                    IsAgentDocumentAbroad = "2",
                    IsRelatedDocumentInSsar = "1",
                    AgentDocumentNo = "6235",
                    AgentDocumentDate = "1404/01/06",
                    AgentDocumentIssuer = "گرگان",
                    SignRequestScriptoriumId = "52539",
                    Ilm = "1",
                    RecordDate = DateTime.MaxValue,
                    Description = "رابطه وکالت تنظیم شده"
                }
            },
                SignElectronicBooks = new List<SignElectronicBook>
            {
                new SignElectronicBook
                {
                    Id = Guid.Parse("f4c784de-2001-4a71-9103-f50a27b40d6c"),
                    ScriptoriumId = "52539",
                    ClassifyNo = 72880,
                    SignRequestId = sr6Id,
                    SignRequestNationalNo = "6234567890",
                    SignRequestPersonId = sr6PersonIds[0],
                    SignDate = "1404/01/06",
                    HashOfFingerprint = "StaticBase64String49",
                    HashOfFile = "StaticBase64String49",
                    DigitalSign = "StaticBase64String205",
                    ConfirmDate = "1404/01/06",
                    ConfirmTime = "15:00:00",
                    RecordDate = DateTime.MaxValue,
                    Ilm = "1",
                    SignCertificateDn = "CN=SampleCertificate-1239,O=Notary,OU=SSAA"
                }
            }
            };
            requests.Add(sr6);

            // --------- REQUEST 7 ----------
            var sr7Id = Guid.Parse("34308507-8f13-4a51-8a83-429f3bbdbd6d");
            var sr7PersonIds = new List<Guid> { Guid.Parse("f16126d0-cadb-46f5-a434-90227c8c5272"), Guid.Parse("d25b01d6-0538-457a-a521-5d219b6f7a12"), Guid.Parse("79f5405a-16ae-4d3e-afca-e154ec15a9d7") };
            var sr7 = new Domain.Entities.SignRequest
            {
                Id = sr7Id,
                ReqNo = "140444452539000002",
                ReqDate = "1404/01/07",
                ReqTime = "16:00:00",
                ScriptoriumId = "52539",
                SignRequestGetterId = "06",
                SignRequestSubjectId = "0106",
                IsCostPaid = "1",
                SumPrices = 41000,
                ReceiptNo = "1234567897",
                PayCostDate = "1404/01/07",
                PayCostTime = "16:00:00",
                PaymentType = "PCPOS",
                BillNo = "1404010112345677",
                NationalNo = "1404021525399000002",
                SecretCode = "789012",
                SignDate = "1404/01/07",
                SignTime = "16:00:00",
                Modifier = "زهرا کریمی",
                ModifyDate = "1404/01/07",
                ModifyTime = "16:00:00",
                Confirmer = "مریم احمدی",
                ConfirmDate = "1404/01/07",
                ConfirmTime = "16:00:00",
                DigitalSign = "StaticBase64String7",
                SignCertificateDn = "CN=SampleCertificate-1240,O=Notary,OU=SSAA",
                IsRemoteRequest = "1",
                State = "2",
                Ilm = "1",
                RecordDate = DateTime.MaxValue,
                IsReadyToPay = "1",
                LegacyId = $"LEGACY_{sr7Id.ToString().Substring(0, 8).ToUpper()}",
                SignText = "امضا انجام شد",
                SignRequestPeople = new List<SignRequestPerson>
            {
                new SignRequestPerson
                {
                    Id = sr7PersonIds[0],
                    SignRequestId = sr7Id,
                    RowNo = 1,
                    SignClassifyNo = 72881,
                    IsOriginal = "1",
                    IsRelated = "2",
                    PersonType = "1",
                    IsIranian = "1",
                    NationalNo = "7234567890",
                    Name = "حمید",
                    Family = "رضایی",
                    BirthDate = "1366/01/01",
                    SexType = "2",
                    FatherName = "مهدی",
                    IdentityIssueLocation = "بوشهر",
                    IdentityNo = "1000007",
                    SeriAlpha = "1",
                    Seri = "16",
                    Serial = "500007",
                    SanaState = "1",
                    MobileNoState = "1",
                    IsSabtahvalChecked = "1",
                    IsSabtahvalCorrect = "1",
                    IsAlive = "1",
                    TfaState = "1",
                    IsFingerprintGotten = "1",
                    MobileNo = "09123456798",
                    PostalCode = "7234567890",
                    Address = "آدرس نمونه در شهر بوشهر",
                    Description = "",
                    ScriptoriumId = "52539",
                    Ilm = "1",
                    RecordDate = DateTime.MaxValue,
                    SignClassifyNoDescription = "شماره ترتیب اصلی"
                },
                new SignRequestPerson
                {
                    Id = sr7PersonIds[1],
                    SignRequestId = sr7Id,
                    RowNo = 2,
                    SignClassifyNo = 72882,
                    IsOriginal = "2",
                    IsRelated = "1",
                    PersonType = "1",
                    IsIranian = "1",
                    NationalNo = "7234567891",
                    Name = "نازیلا",
                    Family = "جعفری",
                    BirthDate = "1368/01/01",
                    SexType = "1",
                    FatherName = "کریم",
                    IdentityIssueLocation = "کرمانشاه",
                    IdentityNo = "2000007",
                    SeriAlpha = "2",
                    Seri = "26",
                    Serial = "500008",
                    SanaState = "1",
                    MobileNoState = "1",
                    IsSabtahvalChecked = "1",
                    IsSabtahvalCorrect = "1",
                    IsAlive = "1",
                    TfaState = "1",
                    IsFingerprintGotten = "1",
                    MobileNo = "09123456799",
                    PostalCode = "7234567891",
                    Address = "آدرس نمونه در شهر کرمانشاه",
                    Description = "",
                    ScriptoriumId = "52539",
                    Ilm = "1",
                    RecordDate = DateTime.MaxValue,
                    SignClassifyNoDescription = "شماره ترتیب وابسته"
                },
                new SignRequestPerson
                {
                    Id = sr7PersonIds[2],
                    SignRequestId = sr7Id,
                    RowNo = 3,
                    SignClassifyNo = 72883,
                    IsOriginal = "2",
                    IsRelated = "1",
                    PersonType = "1",
                    IsIranian = "1",
                    NationalNo = "7234567892",
                    Name = "سپیده",
                    Family = "محمودی",
                    BirthDate = "1371/01/01",
                    SexType = "1",
                    FatherName = "فرهاد",
                    IdentityIssueLocation = "ایلام",
                    IdentityNo = "3000007",
                    SeriAlpha = "2",
                    Seri = "36",
                    Serial = "500009",
                    SanaState = "1",
                    MobileNoState = "1",
                    IsSabtahvalChecked = "1",
                    IsSabtahvalCorrect = "1",
                    IsAlive = "1",
                    TfaState = "1",
                    IsFingerprintGotten = "1",
                    MobileNo = "09123456800",
                    PostalCode = "7234567892",
                    Address = "آدرس نمونه در شهر ایلام",
                    Description = "",
                    ScriptoriumId = "52539",
                    Ilm = "1",
                    RecordDate = DateTime.MaxValue,
                    SignClassifyNoDescription = "شماره ترتیب وابسته"
                }
            },
                SignRequestPersonRelateds = new List<SignRequestPersonRelated>
            {
                new SignRequestPersonRelated
                {
                    Id = Guid.Parse("f8fc9dce-c256-4709-97b8-4590af6cb05f"),
                    SignRequestId = sr7Id,
                    RowNo = 1,
                    MainPersonId = sr7PersonIds[0],
                    AgentPersonId = sr7PersonIds[1],
                    AgentTypeId = "1",
                    IsAgentDocumentAbroad = "2",
                    IsRelatedDocumentInSsar = "1",
                    AgentDocumentNo = "7234",
                    AgentDocumentDate = "1404/01/07",
                    AgentDocumentIssuer = "بوشهر",
                    SignRequestScriptoriumId = "52539",
                    Ilm = "1",
                    RecordDate = DateTime.MaxValue,
                    Description = "رابطه وکالت تنظیم شده"
                },
                new SignRequestPersonRelated
                {
                    Id = Guid.Parse("871fde4e-20a4-46a5-b534-3fa7a5d7858b"),
                    SignRequestId = sr7Id,
                    RowNo = 2,
                    MainPersonId = sr7PersonIds[0],
                    AgentPersonId = sr7PersonIds[2],
                    AgentTypeId = "2",
                    IsAgentDocumentAbroad = "2",
                    IsRelatedDocumentInSsar = "1",
                    AgentDocumentNo = "7235",
                    AgentDocumentDate = "1404/01/07",
                    AgentDocumentIssuer = "کرمانشah",
                    SignRequestScriptoriumId = "52539",
                    Ilm = "1",
                    RecordDate = DateTime.MaxValue,
                    Description = "رابطه وکالت تنظیم شده"
                }
            },
                SignElectronicBooks = new List<SignElectronicBook>
            {
                new SignElectronicBook
                {
                    Id = Guid.Parse("f432b5b7-df20-4e37-805d-d1a8235e0509"),
                    ScriptoriumId = "52539",
                    ClassifyNo = 72881,
                    SignRequestId = sr7Id,
                    SignRequestNationalNo = "7234567890",
                    SignRequestPersonId = sr7PersonIds[0],
                    SignDate = "1404/01/07",
                    HashOfFingerprint = "StaticBase64String50",
                    HashOfFile = "StaticBase64String50",
                    DigitalSign = "StaticBase64String206",
                    ConfirmDate = "1404/01/07",
                    ConfirmTime = "16:00:00",
                    RecordDate = DateTime.MaxValue,
                    Ilm = "1",
                    SignCertificateDn = "CN=SampleCertificate-1240,O=Notary,OU=SSAA"
                }
            }
            };
            requests.Add(sr7);

            // --------- REQUEST 8 ----------
            var sr8Id = Guid.Parse("b9787927-ec18-4321-87e0-da357f082679");
            var sr8PersonIds = new List<Guid> { Guid.Parse("7cf1d770-6605-480c-a507-32a6fd82edce"), Guid.Parse("6493b554-9846-45c1-a51e-4ead8415d534"), Guid.Parse("d634f08d-6424-49ce-bf8e-eddeebb42323") };
            var sr8 = new Domain.Entities.SignRequest
            {
                Id = sr8Id,
                ReqNo = "140444452539000003",
                ReqDate = "1404/01/08",
                ReqTime = "17:00:00",
                ScriptoriumId = "52539",
                SignRequestGetterId = "07",
                SignRequestSubjectId = "0107",
                IsCostPaid = "1",
                SumPrices = 42000,
                ReceiptNo = "1234567898",
                PayCostDate = "1404/01/08",
                PayCostTime = "17:00:00",
                PaymentType = "PCPOS",
                BillNo = "1404010112345678",
                NationalNo = "1404021525399000003",
                SecretCode = "890123",
                SignDate = "1404/01/08",
                SignTime = "17:00:00",
                Modifier = "فاطمه حسینی",
                ModifyDate = "1404/01/08",
                ModifyTime = "17:00:00",
                Confirmer = "زهرا موسوی",
                ConfirmDate = "1404/01/08",
                ConfirmTime = "17:00:00",
                DigitalSign = "StaticBase64String8",
                SignCertificateDn = "CN=SampleCertificate-1241,O=Notary,OU=SSAA",
                IsRemoteRequest = "1",
                State = "2",
                Ilm = "1",
                RecordDate = DateTime.MaxValue,
                IsReadyToPay = "1",
                LegacyId = $"LEGACY_{sr8Id.ToString().Substring(0, 8).ToUpper()}",
                SignText = "امضا انجام شد",
                SignRequestPeople = new List<SignRequestPerson>
            {
                new SignRequestPerson
                {
                    Id = sr8PersonIds[0],
                    SignRequestId = sr8Id,
                    RowNo = 1,
                    SignClassifyNo = 72882,
                    IsOriginal = "1",
                    IsRelated = "2",
                    PersonType = "1",
                    IsIranian = "1",
                    NationalNo = "8234567890",
                    Name = "علیرضا",
                    Family = "کرمی",
                    BirthDate = "1367/01/01",
                    SexType = "2",
                    FatherName = "محمدعلی",
                    IdentityIssueLocation = "اراک",
                    IdentityNo = "1000008",
                    SeriAlpha = "1",
                    Seri = "17",
                    Serial = "500008",
                    SanaState = "1",
                    MobileNoState = "1",
                    IsSabtahvalChecked = "1",
                    IsSabtahvalCorrect = "1",
                    IsAlive = "1",
                    TfaState = "1",
                    IsFingerprintGotten = "1",
                    MobileNo = "09123456801",
                    PostalCode = "8234567890",
                    Address = "آدرس نمونه در شهر اراک",
                    Description = "",
                    ScriptoriumId = "52539",
                    Ilm = "1",
                    RecordDate = DateTime.MaxValue,
                    SignClassifyNoDescription = "شماره ترتیب اصلی"
                },
                new SignRequestPerson
                {
                    Id = sr8PersonIds[1],
                    SignRequestId = sr8Id,
                    RowNo = 2,
                    SignClassifyNo = 72883,
                    IsOriginal = "2",
                    IsRelated = "1",
                    PersonType = "1",
                    IsIranian = "1",
                    NationalNo = "8234567891",
                    Name = "معصومه",
                    Family = "نظری",
                    BirthDate = "1369/01/01",
                    SexType = "1",
                    FatherName = "رحمان",
                    IdentityIssueLocation = "یزد",
                    IdentityNo = "2000008",
                    SeriAlpha = "2",
                    Seri = "27",
                    Serial = "500009",
                    SanaState = "1",
                    MobileNoState = "1",
                    IsSabtahvalChecked = "1",
                    IsSabtahvalCorrect = "1",
                    IsAlive = "1",
                    TfaState = "1",
                    IsFingerprintGotten = "1",
                    MobileNo = "09123456802",
                    PostalCode = "8234567891",
                    Address = "آدرس نمونه در شهر یزد",
                    Description = "",
                    ScriptoriumId = "52539",
                    Ilm = "1",
                    RecordDate = DateTime.MaxValue,
                    SignClassifyNoDescription = "شماره ترتیب وابسته"
                },
                new SignRequestPerson
                {
                    Id = sr8PersonIds[2],
                    SignRequestId = sr8Id,
                    RowNo = 3,
                    SignClassifyNo = 72884,
                    IsOriginal = "2",
                    IsRelated = "1",
                    PersonType = "1",
                    IsIranian = "1",
                    NationalNo = "8234567892",
                    Name = "مهسا",
                    Family = "صادقی",
                    BirthDate = "1372/01/01",
                    SexType = "1",
                    FatherName = "حمیدرضا",
                    IdentityIssueLocation = "قزوین",
                    IdentityNo = "3000008",
                    SeriAlpha = "2",
                    Seri = "37",
                    Serial = "500010",
                    SanaState = "1",
                    MobileNoState = "1",
                    IsSabtahvalChecked = "1",
                    IsSabtahvalCorrect = "1",
                    IsAlive = "1",
                    TfaState = "1",
                    IsFingerprintGotten = "1",
                    MobileNo = "09123456803",
                    PostalCode = "8234567892",
                    Address = "آدرس نمونه در شهر قزوین",
                    Description = "",
                    ScriptoriumId = "52539",
                    Ilm = "1",
                    RecordDate = DateTime.MaxValue,
                    SignClassifyNoDescription = "شماره ترتیب وابسته"
                }
            },
                SignRequestPersonRelateds = new List<SignRequestPersonRelated>
            {
                new SignRequestPersonRelated
                {
                    Id = Guid.Parse("dcadf5b8-b2d3-401a-ae6c-baaa15c22d48"),
                    SignRequestId = sr8Id,
                    RowNo = 1,
                    MainPersonId = sr8PersonIds[0],
                    AgentPersonId = sr8PersonIds[1],
                    AgentTypeId = "1",
                    IsAgentDocumentAbroad = "2",
                    IsRelatedDocumentInSsar = "1",
                    AgentDocumentNo = "8234",
                    AgentDocumentDate = "1404/01/08",
                    AgentDocumentIssuer = "اراک",
                    SignRequestScriptoriumId = "52539",
                    Ilm = "1",
                    RecordDate = DateTime.MaxValue,
                    Description = "رابطه وکالت تنظیم شده"
                },
                new SignRequestPersonRelated
                {
                    Id = Guid.Parse("85e9077a-ec04-4b7d-ad4b-d60ca2d12bbc"),
                    SignRequestId = sr8Id,
                    RowNo = 2,
                    MainPersonId = sr8PersonIds[0],
                    AgentPersonId = sr8PersonIds[2],
                    AgentTypeId = "2",
                    IsAgentDocumentAbroad = "2",
                    IsRelatedDocumentInSsar = "1",
                    AgentDocumentNo = "8235",
                    AgentDocumentDate = "1404/01/08",
                    AgentDocumentIssuer = "یزد",
                    SignRequestScriptoriumId = "52539",
                    Ilm = "1",
                    RecordDate = DateTime.MaxValue,
                    Description = "رابطه وکالت تنظیم شده"
                }
            },
                SignElectronicBooks = new List<SignElectronicBook>
            {
                new SignElectronicBook
                {
                    Id = Guid.Parse("97594b1f-69cb-460c-ba89-b5267025b948"),
                    ScriptoriumId = "52539",
                    ClassifyNo = 72882,
                    SignRequestId = sr8Id,
                    SignRequestNationalNo = "8234567890",
                    SignRequestPersonId = sr8PersonIds[0],
                    SignDate = "1404/01/08",
                    HashOfFingerprint = "StaticBase64String51",
                    HashOfFile = "StaticBase64String51",
                    DigitalSign = "StaticBase64String207",
                    ConfirmDate = "1404/01/08",
                    ConfirmTime = "17:00:00",
                    RecordDate = DateTime.MaxValue,
                    Ilm = "1",
                    SignCertificateDn = "CN=SampleCertificate-1241,O=Notary,OU=SSAA"
                }
            }
            };
            requests.Add(sr8);

            // --------- REQUEST 9 ----------
            var sr9Id = Guid.Parse("7d34f66e-9200-4c7c-8dc3-0389bdcbe23a");
            var sr9PersonIds = new List<Guid> { Guid.Parse("b7668909-8428-4d53-9950-1997621525d7"), Guid.Parse("dc17f364-530e-4f88-be5a-1a35d3075385"), Guid.Parse("88c87e45-7196-46fd-afbe-3cc3ed13c56c") };
            var sr9 = new Domain.Entities.SignRequest
            {
                Id = sr9Id,
                ReqNo = "140444452539000004",
                ReqDate = "1404/01/09",
                ReqTime = "18:00:00",
                ScriptoriumId = "52539",
                SignRequestGetterId = "08",
                SignRequestSubjectId = "0201",
                IsCostPaid = "1",
                SumPrices = 43000,
                ReceiptNo = "1234567899",
                PayCostDate = "1404/01/09",
                PayCostTime = "18:00:00",
                PaymentType = "PCPOS",
                BillNo = "1404010112345679",
                NationalNo = "1404021525399000004",
                SecretCode = "901234",
                SignDate = "1404/01/09",
                SignTime = "18:00:00",
                Modifier = "ناهید محمدی",
                ModifyDate = "1404/01/09",
                ModifyTime = "18:00:00",
                Confirmer = "پگاه رحیمی",
                ConfirmDate = "1404/01/09",
                ConfirmTime = "18:00:00",
                DigitalSign = "StaticBase64String9",
                SignCertificateDn = "CN=SampleCertificate-1242,O=Notary,OU=SSAA",
                IsRemoteRequest = "1",
                State = "2",
                Ilm = "1",
                RecordDate = DateTime.MaxValue,
                IsReadyToPay = "1",
                LegacyId = $"LEGACY_{sr9Id.ToString().Substring(0, 8).ToUpper()}",
                SignText = "امضا انجام شد",
                SignRequestPeople = new List<SignRequestPerson>
            {
                new SignRequestPerson
                {
                    Id = sr9PersonIds[0],
                    SignRequestId = sr9Id,
                    RowNo = 1,
                    SignClassifyNo = 72883,
                    IsOriginal = "1",
                    IsRelated = "2",
                    PersonType = "1",
                    IsIranian = "1",
                    NationalNo = "9234567890",
                    Name = "محمدرضا",
                    Family = "جعفری",
                    BirthDate = "1368/01/01",
                    SexType = "2",
                    FatherName = "عباس",
                    IdentityIssueLocation = "بجنورد",
                    IdentityNo = "1000009",
                    SeriAlpha = "1",
                    Seri = "18",
                    Serial = "500009",
                    SanaState = "1",
                    MobileNoState = "1",
                    IsSabtahvalChecked = "1",
                    IsSabtahvalCorrect = "1",
                    IsAlive = "1",
                    TfaState = "1",
                    IsFingerprintGotten = "1",
                    MobileNo = "09123456804",
                    PostalCode = "9234567890",
                    Address = "آدرس نمونه در شهر بجنورد",
                    Description = "",
                    ScriptoriumId = "52539",
                    Ilm = "1",
                    RecordDate = DateTime.MaxValue,
                    SignClassifyNoDescription = "شماره ترتیب اصلی"
                },
                new SignRequestPerson
                {
                    Id = sr9PersonIds[1],
                    SignRequestId = sr9Id,
                    RowNo = 2,
                    SignClassifyNo = 72884,
                    IsOriginal = "2",
                    IsRelated = "1",
                    PersonType = "1",
                    IsIranian = "1",
                    NationalNo = "9234567891",
                    Name = "زینت",
                    Family = "کرمانی",
                    BirthDate = "1370/01/01",
                    SexType = "1",
                    FatherName = "مهدی",
                    IdentityIssueLocation = "سمنان",
                    IdentityNo = "2000009",
                    SeriAlpha = "2",
                    Seri = "28",
                    Serial = "500010",
                    SanaState = "1",
                    MobileNoState = "1",
                    IsSabtahvalChecked = "1",
                    IsSabtahvalCorrect = "1",
                    IsAlive = "1",
                    TfaState = "1",
                    IsFingerprintGotten = "1",
                    MobileNo = "09123456805",
                    PostalCode = "9234567891",
                    Address = "آدرس نمونه در شهر سمنان",
                    Description = "",
                    ScriptoriumId = "52539",
                    Ilm = "1",
                    RecordDate = DateTime.MaxValue,
                    SignClassifyNoDescription = "شماره ترتیب وابسته"
                },
                new SignRequestPerson
                {
                    Id = sr9PersonIds[2],
                    SignRequestId = sr9Id,
                    RowNo = 3,
                    SignClassifyNo = 72885,
                    IsOriginal = "2",
                    IsRelated = "1",
                    PersonType = "1",
                    IsIranian = "1",
                    NationalNo = "9234567892",
                    Name = "نگین",
                    Family = "حیدری",
                    BirthDate = "1373/01/01",
                    SexType = "1",
                    FatherName = "رضا",
                    IdentityIssueLocation = "زنجان",
                    IdentityNo = "3000009",
                    SeriAlpha = "2",
                    Seri = "38",
                    Serial = "500011",
                    SanaState = "1",
                    MobileNoState = "1",
                    IsSabtahvalChecked = "1",
                    IsSabtahvalCorrect = "1",
                    IsAlive = "1",
                    TfaState = "1",
                    IsFingerprintGotten = "1",
                    MobileNo = "09123456806",
                    PostalCode = "9234567892",
                    Address = "آدرس نمونه در شهر زنجان",
                    Description = "",
                    ScriptoriumId = "52539",
                    Ilm = "1",
                    RecordDate = DateTime.MaxValue,
                    SignClassifyNoDescription = "شماره ترتیب وابسته"
                }
            },
                SignRequestPersonRelateds = new List<SignRequestPersonRelated>
            {
                new SignRequestPersonRelated
                {
                    Id = Guid.Parse("ebb9f49a-19c6-4c84-aa03-e21f012731d0"),
                    SignRequestId = sr9Id,
                    RowNo = 1,
                    MainPersonId = sr9PersonIds[0],
                    AgentPersonId = sr9PersonIds[1],
                    AgentTypeId = "1",
                    IsAgentDocumentAbroad = "2",
                    IsRelatedDocumentInSsar = "1",
                    AgentDocumentNo = "9234",
                    AgentDocumentDate = "1404/01/09",
                    AgentDocumentIssuer = "بجنورد",
                    SignRequestScriptoriumId = "52539",
                    Ilm = "1",
                    RecordDate = DateTime.MaxValue,
                    Description = "رابطه وکالت تنظیم شده"
                },
                new SignRequestPersonRelated
                {
                    Id = Guid.Parse("734d12de-f62a-4882-b863-0f499ad6fe25"),
                    SignRequestId = sr9Id,
                    RowNo = 2,
                    MainPersonId = sr9PersonIds[0],
                    AgentPersonId = sr9PersonIds[2],
                    AgentTypeId = "2",
                    IsAgentDocumentAbroad = "2",
                    IsRelatedDocumentInSsar = "1",
                    AgentDocumentNo = "9235",
                    AgentDocumentDate = "1404/01/09",
                    AgentDocumentIssuer = "سمنان",
                    SignRequestScriptoriumId = "52539",
                    Ilm = "1",
                    RecordDate = DateTime.MaxValue,
                    Description = "رابطه وکالت تنظیم شده"
                }
            },
                SignElectronicBooks = new List<SignElectronicBook>
            {
                new SignElectronicBook
                {
                    Id = Guid.Parse("49b2ddde-7cae-4000-b155-deb84cc38359"),
                    ScriptoriumId = "52539",
                    ClassifyNo = 72883,
                    SignRequestId = sr9Id,
                    SignRequestNationalNo = "9234567890",
                    SignRequestPersonId = sr9PersonIds[0],
                    SignDate = "1404/01/09",
                    HashOfFingerprint = "StaticBase64String52",
                    HashOfFile = "StaticBase64String52",
                    DigitalSign = "StaticBase64String208",
                    ConfirmDate = "1404/01/09",
                    ConfirmTime = "18:00:00",
                    RecordDate = DateTime.MaxValue,
                    Ilm = "1",
                    SignCertificateDn = "CN=SampleCertificate-1242,O=Notary,OU=SSAA"
                }
            }
            };
            requests.Add(sr9);

            // --------- REQUEST 10 ----------
            var sr10Id = Guid.Parse("87c69e83-ad82-449c-a88d-815ceb340b33");
            var sr10PersonIds = new List<Guid> { Guid.Parse("6be54d7c-8ed7-4578-8cb3-827492bb976f"), Guid.Parse("6f629c99-4889-44a9-aea2-c81ad52c8847"), Guid.Parse("92c8b38f-25cb-4503-8b0c-8196ab73998c") };
            var sr10 = new Domain.Entities.SignRequest
            {
                Id = sr10Id,
                ReqNo = "140444452539000005",
                ReqDate = "1404/01/10",
                ReqTime = "19:00:00",
                ScriptoriumId = "52539",
                SignRequestGetterId = "09",
                SignRequestSubjectId = "0202",
                IsCostPaid = "1",
                SumPrices = 44000,
                ReceiptNo = "1234567900",
                PayCostDate = "1404/01/10",
                PayCostTime = "19:00:00",
                PaymentType = "PCPOS",
                BillNo = "1404010112345680",
                NationalNo = "1404021525399000005",
                SecretCode = "012345",
                SignDate = "1404/01/10",
                SignTime = "19:00:00",
                Modifier = "شیرین احمدی",
                ModifyDate = "1404/01/10",
                ModifyTime = "19:00:00",
                Confirmer = "نازیلا محمدی",
                ConfirmDate = "1404/01/10",
                ConfirmTime = "19:00:00",
                DigitalSign = "StaticBase64String10",
                SignCertificateDn = "CN=SampleCertificate-1243,O=Notary,OU=SSAA",
                IsRemoteRequest = "1",
                State = "2",
                Ilm = "1",
                RecordDate = DateTime.MaxValue,
                IsReadyToPay = "1",
                LegacyId = $"LEGACY_{sr10Id.ToString().Substring(0, 8).ToUpper()}",
                SignText = "امضا انجام شد",
                SignRequestPeople = new List<SignRequestPerson>
            {
                new SignRequestPerson
                {
                    Id = sr10PersonIds[0],
                    SignRequestId = sr10Id,
                    RowNo = 1,
                    SignClassifyNo = 72884,
                    IsOriginal = "1",
                    IsRelated = "2",
                    PersonType = "1",
                    IsIranian = "1",
                    NationalNo = "0234567890",
                    Name = "امیرحسین",
                    Family = "مهدوی",
                    BirthDate = "1369/01/01",
                    SexType = "2",
                    FatherName = "محمد",
                    IdentityIssueLocation = "خرم آباد",
                    IdentityNo = "1000010",
                    SeriAlpha = "1",
                    Seri = "19",
                    Serial = "500010",
                    SanaState = "1",
                    MobileNoState = "1",
                    IsSabtahvalChecked = "1",
                    IsSabtahvalCorrect = "1",
                    IsAlive = "1",
                    TfaState = "1",
                    IsFingerprintGotten = "1",
                    MobileNo = "09123456807",
                    PostalCode = "0234567890",
                    Address = "آدرس نمونه در شهر خرم آباد",
                    Description = "",
                    ScriptoriumId = "52539",
                    Ilm = "1",
                    RecordDate = DateTime.MaxValue,
                    SignClassifyNoDescription = "شماره ترتیب اصلی"
                },
                new SignRequestPerson
                {
                    Id = sr10PersonIds[1],
                    SignRequestId = sr10Id,
                    RowNo = 2,
                    SignClassifyNo = 72885,
                    IsOriginal = "2",
                    IsRelated = "1",
                    PersonType = "1",
                    IsIranian = "1",
                    NationalNo = "0234567891",
                    Name = "مهین",
                    Family = "سعادت",
                    BirthDate = "1371/01/01",
                    SexType = "1",
                    FatherName = "حسین",
                    IdentityIssueLocation = "بیرجند",
                    IdentityNo = "2000010",
                    SeriAlpha = "2",
                    Seri = "29",
                    Serial = "500011",
                    SanaState = "1",
                    MobileNoState = "1",
                    IsSabtahvalChecked = "1",
                    IsSabtahvalCorrect = "1",
                    IsAlive = "1",
                    TfaState = "1",
                    IsFingerprintGotten = "1",
                    MobileNo = "09123456808",
                    PostalCode = "0234567891",
                    Address = "آدرس نمونه در شهر بیرجند",
                    Description = "",
                    ScriptoriumId = "52539",
                    Ilm = "1",
                    RecordDate = DateTime.MaxValue,
                    SignClassifyNoDescription = "شماره ترتیب وابسته"
                },
                new SignRequestPerson
                {
                    Id = sr10PersonIds[2],
                    SignRequestId = sr10Id,
                    RowNo = 3,
                    SignClassifyNo = 72886,
                    IsOriginal = "2",
                    IsRelated = "1",
                    PersonType = "1",
                    IsIranian = "1",
                    NationalNo = "0234567892",
                    Name = "راحله",
                    Family = "امانی",
                    BirthDate = "1374/01/01",
                    SexType = "1",
                    FatherName = "علیرضا",
                    IdentityIssueLocation = "یزد",
                    IdentityNo = "3000010",
                    SeriAlpha = "2",
                    Seri = "39",
                    Serial = "500012",
                    SanaState = "1",
                    MobileNoState = "1",
                    IsSabtahvalChecked = "1",
                    IsSabtahvalCorrect = "1",
                    IsAlive = "1",
                    TfaState = "1",
                    IsFingerprintGotten = "1",
                    MobileNo = "09123456809",
                    PostalCode = "0234567892",
                    Address = "آدرس نمونه در شهر یزد",
                    Description = "",
                    ScriptoriumId = "52539",
                    Ilm = "1",
                    RecordDate = DateTime.MaxValue,
                    SignClassifyNoDescription = "شماره ترتیب وابسته"
                }
            },
                SignRequestPersonRelateds = new List<SignRequestPersonRelated>
            {
                new SignRequestPersonRelated
                {
                    Id = Guid.Parse("afd342e7-5f8a-47ee-8675-26c24b91c004"),
                    SignRequestId = sr10Id,
                    RowNo = 1,
                    MainPersonId = sr10PersonIds[0],
                    AgentPersonId = sr10PersonIds[1],
                    AgentTypeId = "1",
                    IsAgentDocumentAbroad = "2",
                    IsRelatedDocumentInSsar = "1",
                    AgentDocumentNo = "0234",
                    AgentDocumentDate = "1404/01/10",
                    AgentDocumentIssuer = "خرم آباد",
                    SignRequestScriptoriumId = "52539",
                    Ilm = "1",
                    RecordDate = DateTime.MaxValue,
                    Description = "رابطه وکالت تنظیم شده"
                },
                new SignRequestPersonRelated
                {
                    Id = Guid.Parse("ccbd4733-b844-4267-a587-686855afe259"),
                    SignRequestId = sr10Id,
                    RowNo = 2,
                    MainPersonId = sr10PersonIds[0],
                    AgentPersonId = sr10PersonIds[2],
                    AgentTypeId = "2",
                    IsAgentDocumentAbroad = "2",
                    IsRelatedDocumentInSsar = "1",
                    AgentDocumentNo = "0235",
                    AgentDocumentDate = "1404/01/10",
                    AgentDocumentIssuer = "بیرجند",
                    SignRequestScriptoriumId = "52539",
                    Ilm = "1",
                    RecordDate = DateTime.MaxValue,
                    Description = "رابطه وکالت تنظیم شده"
                }
            },
                SignElectronicBooks = new List<SignElectronicBook>
            {
                new SignElectronicBook
                {
                    Id = Guid.Parse("428997c5-b373-4dfb-90ef-9ad16e9a3f87"),
                    ScriptoriumId = "52539",
                    ClassifyNo = 72884,
                    SignRequestId = sr10Id,
                    SignRequestNationalNo = "0234567890",
                    SignRequestPersonId = sr10PersonIds[0],
                    SignDate = "1404/01/10",
                    HashOfFingerprint = "StaticBase64String53",
                    HashOfFile = "StaticBase64String53",
                    DigitalSign = "StaticBase64String209",
                    ConfirmDate = "1404/01/10",
                    ConfirmTime = "19:00:00",
                    RecordDate = DateTime.MaxValue,
                    Ilm = "1",
                    SignCertificateDn = "CN=SampleCertificate-1243,O=Notary,OU=SSAA"
                }
            }
            };
            requests.Add(sr10);



            var sr11Id = Guid.Parse("5D58B546-88E9-4734-ACCF-6057C2DA6972");
            var sr11 = new Domain.Entities.SignRequest
            {
                Id = sr1Id,
                ReqNo = "140444457999000011",                    
                ReqDate = "1404/01/01",                          
                ScriptoriumId = "57999",                         
                SignRequestSubjectId = "0101",                   
                ModifyDate = "1404/01/01",                       
                ModifyTime = "10:00:00",                         
                State = "1",                                     
                Ilm = "1",                                       
                RecordDate = DateTime.MaxValue,                  

            };
            requests.Add(sr11);

            return requests;




        }

    }
}