using Dapper;
using Notary.SSAA.BO.Domain.Abstractions;
using Notary.SSAA.BO.Infrastructure.Persistence.Repositories.DapperRepositories.Base;
using Notary.SSAA.BO.SharedKernel.SharedModels;
using Notary.SSAA.BO.SharedKernel.SharedModels.DocumentReport;
using Notary.SSAA.BO.Utilities.Extensions;
using System.Collections.Immutable;
using System.Data;

namespace Notary.SSAA.BO.Infrastructure.Persistence.Repositories.DapperRepositories
{
    public class DocumentReportRepository : DRepository, IDocumentReportRepository
    {
        private readonly IDbConnection _connection;
        public DocumentReportRepository(IDbConnection connection) : base(connection)
        {
            _connection = connection;
        }

        public async Task<DocumentReportViewModel> GetDocumentReport(string id, CancellationToken cancellationToken)
        {
            id = id.ToUpper().Replace("-", "");
            this.EnsureConnectionOpen();
            var mainQuery = string.Format(@"SELECT
CAST(MAIN_DOCUMENT_PERSON.ID AS VARCHAR2(100)) AS MainPersonId   ,
MAIN_DOCUMENT_PERSON.ADDRESS AS MainPersonAddress,
MAIN_DOCUMENT_PERSON.BIRTH_DATE AS MainPersonBirthDate,
MAIN_DOCUMENT_PERSON.COMPANY_REGISTER_DATE AS MainPersonCompanyRegisterDate,
MAIN_DOCUMENT_PERSON.COMPANY_REGISTER_LOCATION AS MainPersonCompanyRegisterLocation,
MAIN_DOCUMENT_PERSON.COMPANY_REGISTER_NO AS MainPersonCompanyRegisterNo,
MAIN_DOCUMENT_PERSON.FAMILY AS MainPersonFamily,
MAIN_DOCUMENT_PERSON.NAME AS MainPersonName,
MAIN_DOCUMENT_PERSON.FATHER_NAME AS MainPersonFatherName,
MAIN_DOCUMENT_PERSON.IDENTITY_ISSUE_LOCATION AS MainPersonIdentityIssueLocation,
MAIN_DOCUMENT_PERSON.IDENTITY_NO AS MainPersonIdentityNo,
MAIN_DOCUMENT_PERSON.IS_ORIGINAL AS MainPersonIsOrginal,
MAIN_DOCUMENT_PERSON.LEGALPERSON_NATURE_ID AS MainLegalPersonNatureId ,
MAIN_DOCUMENT_PERSON.COMPANY_TYPE_ID AS MainPersonCompanyTypeId,
MAIN_DOCUMENT_PERSON.IS_IRANIAN AS MainPersonIsIranian ,
MAIN_DOCUMENT_PERSON.NATIONAL_NO AS MainPersonNationalNo,
MAIN_DOCUMENT_PERSON.NATIONALITY_ID AS MainPersonNationalityId,
MAIN_DOCUMENT_PERSON.NATIONALITY AS MainPersonNationality,
MAIN_DOCUMENT_PERSON.DOCUMENT_PERSON_TYPE_ID AS MainPersonTypeId,
MAIN_DOCUMENT_PERSON.POSTAL_CODE AS MainPersonPostalCode,
--MAIN_DOCUMENT_PERSON.SEX_TYPE AS MainPersonSexType,
(CASE WHEN MAIN_DOCUMENT_PERSON.SEX_TYPE = '1' THEN 'خانم' ELSE 'آقا' END) AS MainPersonSexType,
MAIN_DOCUMENT_PERSON.TEL AS MainPersonTel,
MAIN_DOCUMENT_PERSON.ROW_NO AS MainPersonRowNo,
MAIN_DOCUMENT_PERSON.DESCRIPTION AS MainPersonDescription ,
MAIN_DOCUMENT_PERSON.PERSON_TYPE AS MainPersonType,
MAIN_DOCUMENT_PERSON.LEGALPERSON_TYPE_ID AS MainLegalPersonTypeId,
MAIN_DOCUMENT_PERSON.LAST_LEGAL_PAPER_DATE AS MainPersonLastLegalPaperDate,
MAIN_DOCUMENT_PERSON.LAST_LEGAL_PAPER_NO AS MainPersonLastLegalPaperNo,
DOCUMENT_PERSON_TYPE.SINGULAR_TITLE AS PersonTypeSingularTitle,
DOCUMENT_PERSON_TYPE.PLURAL_TITLE AS PersonTypePluralTitle ,
DOCUMENT_PERSON_TYPE.PRINT_SINGULAR_TITLE AS  PersonTypePrintSingularTitle,
DOCUMENT_PERSON_TYPE.PRINT_PLURAL_TITLE AS PersonTypePrintPluralTitle,
DOCUMENT_PERSON_TYPE.IS_OWNER AS IsOwner ,
CAST(PERSON_FINGERPRINT.FINGERPRINT_IMAGE_FILE AS VARCHAR2(1000))  AS PersonFingerPrintImageFile,
CAST(DOCUMENT.ID AS VARCHAR2(100)) AS DocumentId,
DOCUMENT.SCRIPTORIUM_ID AS ScriptoriumId ,
DOCUMENT.DOCUMENT_DATE AS DocumentDate,
DOCUMENT.REQUEST_DATE AS RequestDate,
DOCUMENT.REQUEST_TIME AS RequestTime,
DOCUMENT.CLASSIFY_NO AS ClassifyNo,
DOCUMENT.DOCUMENT_SECRET_CODE AS DocumentSecretCode,
DOCUMENT.GET_DOCUMENT_NO_DATE AS GetDocumentNoDate,
DOCUMENT.NATIONAL_NO AS DocumentNationalNo,
DOCUMENT.BOOK_VOLUME_NO AS BookVolumeNo,
DOCUMENT.BOOK_PAPERS_NO AS BookPaperType,
DOCUMENT.PRICE AS DocumentPrice,
DOCUMENT.SABT_PRICE AS DocumentSabtPrice,
DOCUMENT.SIGN_DATE AS DocumentSignDate,
DOCUMENT.SIGN_TIME AS DocumentSignTime,
DOCUMENT.DOCUMENT_TYPE_TITLE AS OtherDocumentTypeTitle,
DOCUMENT.STATE AS DocumentState,
DOCUMENT.IS_BASED_JUDGMENT AS IsBaseJudgment,
DOCUMENT.DOCUMENT_TYPE_ID AS DocumentTypeId,
DOCUMENT.RELATED_DOCUMENT_NO AS RelatedDocumentNo,
DOCUMENT_TYPE.TITLE AS DocumentTypeTitle,
DOCUMENT_TYPE.IS_SUPPORTIVE AS DocumentTypeIsSupportive,
DOCUMENT_TYPE.CASE_TITLE AS DocumentTypeCaseTitle,
DOCUMENT_TYPE.WEALTH_TYPE AS WealthType ,
DOCUMENT_TYPE.HAS_ASSET AS HasAsset,
DOCUMENT_INFO_CONFIRM.SARDAFTAR_CONFIRM_DATE AS SardaftarConfirmDate,
DOCUMENT_INFO_CONFIRM.DAFTARYAR_NAME_FAMILY AS DaftaryarConfirmFullName,
DOCUMENT_INFO_CONFIRM.CONFIRM_DATE AS ConfirmDate,
DOCUMENT_INFO_CONFIRM.CONFIRMER_NAME_FAMILY AS SardaftarConfirmFullName,
DOCUMENT_INFO_CONFIRM.CREATE_DATE AS ConfirmCreateDate,
DOCUMENT_INFO_CONFIRM.CREATOR_NAME_FAMILY AS CreatorNameFamily,
DOCUMENT_INFO_TEXT.DOCUMENT_TEXT_FONT_SIZE AS TextFontSize,
DOCUMENT_INFO_TEXT.DOCUMENT_DESCRIPTION AS DocumentTextDescription,
DOCUMENT_INFO_TEXT.PRINT_MODE AS TextPrintMode,
DOCUMENT_INFO_TEXT.LEGAL_TEXT AS LegalText,
DOCUMENT_INFO_OTHER.HAS_MULTIPLE_ADVOCACY_PERMIT AS HasMultipleAdvocacyPermit,
DOCUMENT_INFO_OTHER.IS_DOCUMENT_BRIEF AS IsDocumentBrief,
DOCUMENT_INFO_OTHER.DIVIDED_SECTIONS_COUNT AS DividedSectionsCount,
DOCUMENT_INFO_OTHER.REGISTER_COUNT AS RegisterCount,
DOCUMENT_INFO_OTHER.HAS_DISMISSAL_PERMIT AS HasDismissalPermit,
DOCUMENT_INFO_OTHER.HAS_ADVOCACY_TO_OTHERS_PERMIT AS HasAdvocacyToOthersPermit,
DOCUMENT_INFO_OTHER.HAS_TIME AS HasTime,
DOCUMENT_INFO_OTHER.ADVOCACY_END_DATE AS AdvocacyEndDate,
DOCUMENT_INFO_OTHER.RENT_START_DATE AS RentStartDate,
DOCUMENT_INFO_OTHER.RENT_DURATION AS RentDuration,
DOCUMENT_INFO_OTHER.IS_PEACE_FOR_LIFETIME AS IsPeaceForLifeTime,
DOCUMENT_INFO_OTHER.PEACE_DURATION AS PeaceDuration,
DOCUMENT_INFO_OTHER.HAGHE_ENTEFAE AS HagheEntefae,
DOCUMENT_INFO_OTHER.VAGHF_TYPE AS VaghfType,
DOCUMENT_INFO_OTHER.IS_RENT_WITH_SARGHOFLI AS IsRentWithSarghofli,
DOCUMENT_INFO_OTHER.MORTAGE_DURATION AS MortageDuration,
DOCUMENT_INFO_OTHER.MORTAGE_TIME_UNIT_ID AS MortageTimeUnitId,
DOCUMENT_INFO_JUDGEMENT.ISSUE_DATE AS JudgmentIssueDate,
DOCUMENT_INFO_JUDGEMENT.ISSUE_NO AS JudgmentIssueNo,
DOCUMENT_INFO_JUDGEMENT.ISSUER_NAME AS JudgmentIssueName,
DOCUMENT_INFO_JUDGEMENT.CASE_CLASSIFY_NO AS JudgmentIssueCaseClassifyNo,
DOCUMENT_INFO_JUDGEMENT.DOCUMENT_JUDGEMENT_TYPE_ID AS JudmentTypeId,
DOCUMENT_JUDGEMENT_TYPE.TITLE AS JudmentTypeTitle,
DOCUMENT_COST.PRICE AS CostPrice,
DOCUMENT_COST.COST_TYPE_ID AS CostTypeId,
COST_TYPE.TITLE AS CostTypeTitle,
(SELECT DETAIL_QUOTA FROM DOCUMENT_ESTATE_QUOTA WHERE DOCUMENT_PERSON_ID = MAIN_DOCUMENT_PERSON.ID AND DOCUMENT_ESTATE_ID = DOCUMENT_ESTATE.ID) AS EstateQuotaDetailQuota,
(SELECT TOTAL_QUOTA FROM DOCUMENT_ESTATE_QUOTA WHERE DOCUMENT_PERSON_ID = MAIN_DOCUMENT_PERSON.ID AND DOCUMENT_ESTATE_ID = DOCUMENT_ESTATE.ID) AS EstateQuotaTotalQuota,
(SELECT QUOTA_TEXT FROM DOCUMENT_ESTATE_QUOTA WHERE DOCUMENT_PERSON_ID = MAIN_DOCUMENT_PERSON.ID AND DOCUMENT_ESTATE_ID = DOCUMENT_ESTATE.ID) AS EstateQuotaText,
(SELECT  CAST(DOCUMENT_PERSON_ID AS VARCHAR2(100) ) FROM DOCUMENT_ESTATE_QUOTA WHERE DOCUMENT_PERSON_ID = MAIN_DOCUMENT_PERSON.ID AND DOCUMENT_ESTATE_ID = DOCUMENT_ESTATE.ID) AS EstateQuotaPersonId,
(SELECT SELL_DETAIL_QUOTA FROM DOCUMENT_ESTATE_QUOTA_DETAILS WHERE DOCUMENT_PERSON_SELLER_ID = MAIN_DOCUMENT_PERSON.ID AND DOCUMENT_ESTATE_ID = DOCUMENT_ESTATE.ID) AS EstateQuotaDetailSellerDetailQuota,
(SELECT SELL_TOTAL_QUOTA FROM DOCUMENT_ESTATE_QUOTA_DETAILS WHERE DOCUMENT_PERSON_SELLER_ID = MAIN_DOCUMENT_PERSON.ID AND DOCUMENT_ESTATE_ID = DOCUMENT_ESTATE.ID) AS EstateQuotaDetailSellerTotalQuota,
(SELECT SELL_DETAIL_QUOTA FROM DOCUMENT_ESTATE_QUOTA_DETAILS WHERE DOCUMENT_PERSON_BUYER_ID = MAIN_DOCUMENT_PERSON.ID AND DOCUMENT_ESTATE_ID = DOCUMENT_ESTATE.ID) AS EstateQuotaDetailByuerDetailQuota,
(SELECT SELL_TOTAL_QUOTA FROM DOCUMENT_ESTATE_QUOTA_DETAILS WHERE DOCUMENT_PERSON_BUYER_ID = MAIN_DOCUMENT_PERSON.ID AND DOCUMENT_ESTATE_ID = DOCUMENT_ESTATE.ID) AS EstateQuotaDetailByuerTotalQuota,
(SELECT CAST(DOCUMENT_PERSON_BUYER_ID AS VARCHAR2(100) )FROM DOCUMENT_ESTATE_QUOTA_DETAILS WHERE DOCUMENT_PERSON_BUYER_ID = MAIN_DOCUMENT_PERSON.ID AND DOCUMENT_ESTATE_ID = DOCUMENT_ESTATE.ID) AS EstateQuotaDetailBuyerPersonId,
(SELECT CAST(DOCUMENT_PERSON_SELLER_ID AS VARCHAR2(100) )FROM DOCUMENT_ESTATE_QUOTA_DETAILS WHERE DOCUMENT_PERSON_SELLER_ID = MAIN_DOCUMENT_PERSON.ID AND DOCUMENT_ESTATE_ID = DOCUMENT_ESTATE.ID) AS EstateQuotaDetailSellerPersonId,
(SELECT OWNERSHIP_DETAIL_QUOTA FROM DOCUMENT_ESTATE_QUOTA_DETAILS WHERE DOCUMENT_PERSON_SELLER_ID = MAIN_DOCUMENT_PERSON.ID AND DOCUMENT_ESTATE_ID = DOCUMENT_ESTATE.ID) AS EstateQuotaDetailOwnerShipDetailQuota,
(SELECT OWNERSHIP_TOTAL_QUOTA FROM DOCUMENT_ESTATE_QUOTA_DETAILS WHERE DOCUMENT_PERSON_SELLER_ID = MAIN_DOCUMENT_PERSON.ID AND DOCUMENT_ESTATE_ID = DOCUMENT_ESTATE.ID) AS EstateQuotaDetailOwnerShipTotalQuota,
(SELECT DOCUMENT_INQUIRY.REPLY_DETAIL_QUOTA FROM DOCUMENT_INQUIRY , DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT 
WHERE DOCUMENT_INQUIRY.ESTATE_INQUIRIES_ID = to_char(DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.ESTATE_INQUIRIES_ID) 
AND DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.DOCUMENT_PERSON_ID =  MAIN_DOCUMENT_PERSON.ID AND DOCUMENT_ID = DOCUMENT.ID) AS DocumentInquiryReplyDetailQuota,
(SELECT CAST(DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.DOCUMENT_PERSON_ID AS VARCHAR2(100)  )FROM DOCUMENT_INQUIRY , DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT 
WHERE DOCUMENT_INQUIRY.ESTATE_INQUIRIES_ID = to_char(DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.ESTATE_INQUIRIES_ID) 
AND DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.DOCUMENT_PERSON_ID =  MAIN_DOCUMENT_PERSON.ID AND DOCUMENT_ID = DOCUMENT.ID) AS DocumentInquiryPersonId,
(SELECT DOCUMENT_INQUIRY.REPLY_TOTAL_QUOTA FROM DOCUMENT_INQUIRY , DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT 
WHERE DOCUMENT_INQUIRY.ESTATE_INQUIRIES_ID = to_char(DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.ESTATE_INQUIRIES_ID) 
AND DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.DOCUMENT_PERSON_ID =  MAIN_DOCUMENT_PERSON.ID AND DOCUMENT_ID = DOCUMENT.ID) AS DocumentInquiryReplyTotalQuota,
(SELECT CAST(DOCUMENT_INQUIRY.REPLY_QUOTA_TEXT AS VARCHAR2(1000))  FROM DOCUMENT_INQUIRY , DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT 
WHERE DOCUMENT_INQUIRY.ESTATE_INQUIRIES_ID = to_char(DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.ESTATE_INQUIRIES_ID) 
AND DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.DOCUMENT_PERSON_ID =  MAIN_DOCUMENT_PERSON.ID AND DOCUMENT_ID = DOCUMENT.ID) AS DocumentInquiryReplyQuotaText,
(SELECT DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.OWNERSHIP_DOCUMENT_TYPE FROM DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT WHERE DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.DOCUMENT_ESTATE_ID = DOCUMENT_ESTATE.ID
AND DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.DOCUMENT_PERSON_ID = MAIN_DOCUMENT_PERSON.ID) AS EstateOwnershipDocumentType,
(SELECT DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.ESTATE_ELECTRONIC_PAGE_NO FROM DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT WHERE DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.DOCUMENT_ESTATE_ID = DOCUMENT_ESTATE.ID
AND DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.DOCUMENT_PERSON_ID = MAIN_DOCUMENT_PERSON.ID) AS EstateOwnershipDocumentEloctronicPageNo,
(SELECT DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.ESTATE_IS_REPLACEMENT_DOCUMENT FROM DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT WHERE DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.DOCUMENT_ESTATE_ID = DOCUMENT_ESTATE.ID
AND DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.DOCUMENT_PERSON_ID = MAIN_DOCUMENT_PERSON.ID) AS EstateOwnershipDocumentIsReplacment,
(SELECT DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.ESTATE_DOCUMENT_TYPE FROM DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT WHERE DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.DOCUMENT_ESTATE_ID = DOCUMENT_ESTATE.ID
AND DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.DOCUMENT_PERSON_ID = MAIN_DOCUMENT_PERSON.ID) AS EstateDocumentType,
(SELECT DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.ESTATE_SABT_NO FROM DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT WHERE DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.DOCUMENT_ESTATE_ID = DOCUMENT_ESTATE.ID
AND DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.DOCUMENT_PERSON_ID = MAIN_DOCUMENT_PERSON.ID) AS EstateOwnershipSabtNo,
(SELECT DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.ESTATE_DOCUMENT_NO FROM DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT WHERE DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.DOCUMENT_ESTATE_ID = DOCUMENT_ESTATE.ID
AND DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.DOCUMENT_PERSON_ID = MAIN_DOCUMENT_PERSON.ID) AS EstateOwnershipDocNo,
(SELECT DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.ESTATE_BOOK_NO FROM DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT WHERE DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.DOCUMENT_ESTATE_ID = DOCUMENT_ESTATE.ID
AND DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.DOCUMENT_PERSON_ID = MAIN_DOCUMENT_PERSON.ID) AS EstateOwnershipBookNo,
(SELECT DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.ESTATE_BOOK_PAGE_NO FROM DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT WHERE DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.DOCUMENT_ESTATE_ID = DOCUMENT_ESTATE.ID
AND DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.DOCUMENT_PERSON_ID = MAIN_DOCUMENT_PERSON.ID) AS EstateOwnershipBookPageNo,
(SELECT ESTATE_SERIDAFTAR.TITLE FROM DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT , ESTATE_SERIDAFTAR  WHERE DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.DOCUMENT_ESTATE_ID = DOCUMENT_ESTATE.ID
AND DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.DOCUMENT_PERSON_ID = MAIN_DOCUMENT_PERSON.ID AND DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.ESTATE_SERIDAFTAR_ID = ESTATE_SERIDAFTAR.ID) AS EstateOwnershipSardaftar,
(SELECT DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.ESTATE_BOOK_TYPE FROM DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT WHERE DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.DOCUMENT_ESTATE_ID = DOCUMENT_ESTATE.ID
AND DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.DOCUMENT_PERSON_ID = MAIN_DOCUMENT_PERSON.ID) AS EstateOwnershipBooktype,
(SELECT DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.SABT_STATE_REPORT_NO FROM DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT WHERE DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.DOCUMENT_ESTATE_ID = DOCUMENT_ESTATE.ID
AND DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.DOCUMENT_PERSON_ID = MAIN_DOCUMENT_PERSON.ID) AS EstateOwnershipSabtStateReportNo,
(SELECT DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.SABT_STATE_REPORT_DATE FROM DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT WHERE DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.DOCUMENT_ESTATE_ID = DOCUMENT_ESTATE.ID
AND DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.DOCUMENT_PERSON_ID = MAIN_DOCUMENT_PERSON.ID) AS EstateOwnershipSabtStateReportDate,
(SELECT DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.SABT_STATE_REPORT_UNIT_NAME FROM DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT WHERE DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.DOCUMENT_ESTATE_ID = DOCUMENT_ESTATE.ID
AND DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.DOCUMENT_PERSON_ID = MAIN_DOCUMENT_PERSON.ID) AS EstateOwnershipSabtStateReportUnitName,
(SELECT DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.NOTARY_NO FROM DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT WHERE DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.DOCUMENT_ESTATE_ID = DOCUMENT_ESTATE.ID
AND DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.DOCUMENT_PERSON_ID = MAIN_DOCUMENT_PERSON.ID) AS EstateOwnershipNotaryNo,
(SELECT DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.NOTARY_LOCATION FROM DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT WHERE DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.DOCUMENT_ESTATE_ID = DOCUMENT_ESTATE.ID
AND DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.DOCUMENT_PERSON_ID = MAIN_DOCUMENT_PERSON.ID) AS EstateOwnershipNotaryLocation,
(SELECT DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.NOTARY_DOCUMENT_NO FROM DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT WHERE DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.DOCUMENT_ESTATE_ID = DOCUMENT_ESTATE.ID
AND DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.DOCUMENT_PERSON_ID = MAIN_DOCUMENT_PERSON.ID) AS EstateOwnershipNotaryDocumentNo,
(SELECT DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.NOTARY_DOCUMENT_DATE FROM DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT WHERE DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.DOCUMENT_ESTATE_ID = DOCUMENT_ESTATE.ID
AND DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.DOCUMENT_PERSON_ID = MAIN_DOCUMENT_PERSON.ID) AS EstateOwnershipNotaryDocumentDate,
(SELECT DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.DESCRIPTION FROM DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT WHERE DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.DOCUMENT_ESTATE_ID = DOCUMENT_ESTATE.ID
AND DOCUMENT_ESTATE_OWNERSHIP_DOCUMENT.DOCUMENT_PERSON_ID = MAIN_DOCUMENT_PERSON.ID) AS EstateOwnershipDescription,
CAST(DOCUMENT_INQUIRY.REPLY_DATE AS VARCHAR2(10))  AS InquiryReplyDate,
DOCUMENT_INQUIRY.REPLY_NO  AS InquiryReplyNo,
DOCUMENT_INQUIRY.CONDITIONS  AS InquiryDescription,
(SELECT DOCUMENT_INQUIRY_ORGANIZATION.TITLE FROM DOCUMENT_INQUIRY_ORGANIZATION WHERE ID = DOCUMENT_INQUIRY.DOCUMENT_INQUIRY_ORGANIZATION_ID) AS InquiryOrganizationTitle,
CAST(DOCUMENT_PERSON_RELATED.AGENT_PERSON_ID AS VARCHAR2(100)) AS AgentPersonId,
CAST(DOCUMENT_PERSON_RELATED.MAIN_PERSON_ID AS VARCHAR2(100)) AS MainAgentPersonId,
RELIABLE_PERSON_REASON.CODE AS ReliablePersonReasonCode,
DOCUMENT_PERSON_RELATED.AGENT_DOCUMENT_NO AS RelatedAgentDocumentNo ,
DOCUMENT_PERSON_RELATED.AGENT_DOCUMENT_DATE AS RelatedAgentDocumentDate,
DOCUMENT_PERSON_RELATED.AGENT_DOCUMENT_ISSUER AS RelatedAgentDocumentIssuer,
AGENT_TYPE.TITLE AS AgentTypeTitle,
AGENT_TYPE.ROOT AS AgentTypeRoot,
AGENT_TYPE.CODE AS AgentTypeCode,
AGENT_DOCUMENT_PERSON.NAME AS AgentPersonName,
AGENT_DOCUMENT_PERSON.FAMILY AS AgentPersonFamily ,
CAST(DOCUMENT_ESTATE.ID AS VARCHAR2(100)) AS EstateId,
DOCUMENT_ESTATE.DESCRIPTION AS EstateDescription,
DOCUMENT_ESTATE.ADDRESS AS EstateAddress,
DOCUMENT_ESTATE.AREA AS EstateArea,
DOCUMENT_ESTATE.AREA_DESCRIPTION AS EstateAreaDescription,
DOCUMENT_ESTATE.DOCUMENT_ESTATE_TYPE_ID AS EstateTypeId , --ONotaryAssetTypeId
DOCUMENT_ESTATE_TYPE.TITLE AS EstateTypeTitle ,--ONotaryAssetTypeTitle
DOCUMENT_ESTATE.PRICE AS EstatePrice,
DOCUMENT_ESTATE.ESTATE_SECTION_ID AS EstateSectionId ,
DOCUMENT_ESTATE.BASIC_PLAQUE AS EstateBasicPlaque,
DOCUMENT_ESTATE.BASIC_PLAQUE_HAS_REMAIN AS EstateBasicPlaqueHasRemain,
DOCUMENT_ESTATE.BLOCK AS EstateBlock,
DOCUMENT_ESTATE.COMMONS AS EstateCommons,
DOCUMENT_ESTATE.DIRECTION AS EstateDirection,
DOCUMENT_ESTATE.DIV_FROM_BASIC_PLAQUE AS EstateDivFromBasicPlaque,
DOCUMENT_ESTATE.DIV_FROM_SECONDARY_PLAQUE AS EstateDivFromSecondaryPlaque,
DOCUMENT_ESTATE.FLOOR AS EstateFloor ,
DOCUMENT_ESTATE.GEO_LOCATION_ID AS EstateGeoLocationId ,
DOCUMENT_ESTATE.ESTATE_SUBSECTION_ID AS EstateSubSectionId,
DOCUMENT_ESTATE.EVACUATION_DESCRIPTION AS EstateEvacuationDescription,
DOCUMENT_ESTATE.IMMOVALE_TYPE AS EstateImmovaleType ,
DOCUMENT_ESTATE.LIMITS AS EstateLimits,
DOCUMENT_ESTATE.LOCATION_TYPE AS EstateLocationType,
DOCUMENT_ESTATE.UNIT_ID AS EstateUnitId,
DOCUMENT_ESTATE.OLD_SALE_DESCRIPTION AS EstateOldSaleDescription,
DOCUMENT_ESTATE.PIECE AS EstatePiece ,
DOCUMENT_ESTATE.PLAQUE_TEXT AS EstatePlaqueText ,
DOCUMENT_ESTATE.SECONDARY_PLAQUE_HAS_REMAIN AS EstateSecondaryPlaqueHasRemain ,
DOCUMENT_ESTATE.SECONDARY_PLAQUE AS EstateSecondaryPlaque,
DOCUMENT_ESTATE.MUNICIPALITY_NO AS EstateMunicipalityNo ,
DOCUMENT_ESTATE.MUNICIPALITY_DATE AS EstateMunicipalityDate,
DOCUMENT_ESTATE.MUNICIPALITY_ISSUER AS EstateMunicipalityIssuer,
DOCUMENT_ESTATE.SEPARATION_DATE AS EstateSeprationDate,
DOCUMENT_ESTATE.SEPARATION_NO AS EstateSeprationNo ,
DOCUMENT_ESTATE.SEPARATION_ISSUER AS EstateSeprationIssuer,
DOCUMENT_ESTATE.QUOTA_TEXT AS EstateQuotaText,
DOCUMENT_ESTATE.RECEIVER_BASIC_PLAQUE AS EstateReceiverBasicPlaque,
DOCUMENT_ESTATE.RECEIVER_BASIC_PLAQUE_HAS_REMAIN AS EstateReceiverBasicPlaqueHasRemain,
DOCUMENT_ESTATE.RECEIVER_DIV_FROM_BASIC_PLAQUE AS EstateReceiverDivFromBasicPlaque,
DOCUMENT_ESTATE.RECEIVER_DIV_FROM_SECONDARY_PLAQUE AS EstateReceiverDivFromSecondaryPlaque,
DOCUMENT_ESTATE.RECEIVER_PLAQUE_TEXT AS EstateReceiverPlaqueText ,
DOCUMENT_ESTATE.RECEIVER_SECONDARY_PLAQUE_HAS_REMAIN AS EstateReceiverSecondaryPlaqueHasRemain,
DOCUMENT_ESTATE.IS_REMORTAGE AS EstateIsRemortage,
DOCUMENT_ESTATE.ATTACHMENT_SPECIFICATIONS AS EstateAttachmentSpecifications,
DOCUMENT_ESTATE.ATTACHMENT_DESCRIPTION AS EstateAttachmentDescription,
DOCUMENT_ESTATE.ATTACHMENT_TYPE AS EstateAttachmentType,
DOCUMENT_ESTATE.ATTACHMENT_TYPE_OTHERS AS EstateAttachmentTypeOther,
DOCUMENT_ESTATE.IS_ATTACHMENT AS EstateIsAttachment,
DOCUMENT_ESTATE.SELL_DETAIL_QUOTA AS EstateSellDetailQuota,
DOCUMENT_ESTATE.SELL_TOTAL_QUOTA AS EstateSellTotalQuota,
DOCUMENT_ESTATE.IS_PROPORTIONATE_QUOTA AS EstateIsProportionateQuota,
DOCUMENT_ESTATE.IS_REGISTERED AS EstateIsRegistered,
(SELECT ES.TITLE FROM ESTATE_SECTION es WHERE ES.ID = DOCUMENT_ESTATE.ESTATE_SECTION_ID ) AS EstateSectionTitle,
(SELECT ES.TITLE FROM ESTATE_SUBSECTION es WHERE ES.ID = DOCUMENT_ESTATE.ESTATE_SUBSECTION_ID ) AS EstateSubSectionTitle,
DOCUMENT_ESTATE.ROW_NO AS EstateRowNo ,
DOCUMENT_VEHICLE.CARD_NO AS VehicleCardNo ,
DOCUMENT_VEHICLE.CHASSIS_NO AS VehicleChassisNo,
DOCUMENT_VEHICLE.COLOR AS VehicleColor ,
DOCUMENT_VEHICLE.CYLINDER_COUNT AS VehicleCylinderCount,
DOCUMENT_VEHICLE.DUTY_FICHE_NO AS VehicleDutyFicheNo,
DOCUMENT_VEHICLE.ENGINE_CAPACITY AS VehicleEngineCapacity,
DOCUMENT_VEHICLE.ENGINE_NO AS VehicleEngineNo ,
DOCUMENT_VEHICLE.NUMBERING_LOCATION AS VehicleNumberingLocation,
DOCUMENT_VEHICLE.OTHER_INFO AS VehicleOtherInfo,
DOCUMENT_VEHICLE.INSSURANCE_CO AS VehicleInssuranceCo,
DOCUMENT_VEHICLE.INSSURANCE_NO AS VehicleInssuranceNo,
DOCUMENT_VEHICLE.OLD_DOCUMENT_DATE AS VehicleOldDocumentDate,
DOCUMENT_VEHICLE.OLD_DOCUMENT_ISSUER AS VehicleOldDocumentIssuer ,
DOCUMENT_VEHICLE.OLD_DOCUMENT_NO AS VehicleOldDocumentNo ,
DOCUMENT_VEHICLE.PLAQUE_NO_ALPHA_BUYER AS VehiclePlaqueNoAlphaBuyer,
DOCUMENT_VEHICLE.PLAQUE_NO_ALPHA_SELLER AS VehiclePlaqueNoAlphaSeller,
DOCUMENT_VEHICLE.PLAQUE_NO1_SELLER AS VehiclePlaqueNo1Seller,
DOCUMENT_VEHICLE.PLAQUE_NO1_BUYER AS VehiclePlaqueNo1Buyer,
DOCUMENT_VEHICLE.PLAQUE_NO2_SELLER AS VehiclePlaqueNo2Seller,
DOCUMENT_VEHICLE.PLAQUE_NO2_BUYER AS VehiclePlaqueNo2Buyer,
DOCUMENT_VEHICLE.PLAQUE_SERI_SELLER AS VehiclePlaqueSeriSeller,
DOCUMENT_VEHICLE.PLAQUE_SERI_BUYER AS VehiclePlaqueSeriBuyer,
DOCUMENT_VEHICLE.PLAQUE_SELLER AS VehiclePlaqueSeller,
DOCUMENT_VEHICLE_TIP.TITLE AS VehicleTipTitle,
DOCUMENT_VEHICLE.OWNERSHIP_PRINTED_DOCUMENT_NO AS VehicleOwnershipPrintedDocumentNo,
CAST(DOCUMENT_VEHICLE.ID AS VARCHAR2(100)) AS DocumentVehicleId,
DOCUMENT_ESTATE_SEPARATION_PIECES.AREA AS EstateSeprationPiecesArea,
DOCUMENT_ESTATE_SEPARATION_PIECES.PIECE_NO AS EstateSeprationPiecesNo,
ESTATE_PIECE_TYPE.TITLE AS EstatePieceType,
DOCUMENT_ESTATE_SEPARATION_PIECES.FLOOR AS EstateSeprationPiecesFloor,
DOCUMENT_ESTATE_SEPARATION_PIECES.DIRECTION AS EstateSeprationPiecesDirection,
CAST(DOCUMENT_ESTATE_SEPARATION_PIECES.NORTH_LIMITS AS VARCHAR2(100)) AS EstateSeprationPiecesNorthLimit,
CAST(DOCUMENT_ESTATE_SEPARATION_PIECES.WESTERN_LIMITS AS VARCHAR2(100)) AS EstateSeprationPiecesWesternLimit,
CAST(DOCUMENT_ESTATE_SEPARATION_PIECES.EASTERN_LIMITS AS VARCHAR2(100)) AS EstateSeprationPiecesEasternLimit,
CAST(DOCUMENT_ESTATE_SEPARATION_PIECES.SOUTH_LIMITS AS VARCHAR2(100)) AS EstateSeprationPiecesSouthLimit,
CAST(DOCUMENT_ESTATE_SEPARATION_PIECES.COMMONS AS VARCHAR2(100)) AS EstateSeprationPiecesCommons ,
CAST(DOCUMENT_ESTATE_SEPARATION_PIECES.RIGHTS AS VARCHAR2(100)) AS EstateSeprationPiecesRights,
CAST(DOCUMENT_ESTATE_SEPARATION_PIECES.DESCRIPTION AS VARCHAR2(100)) AS EstateSeprationPiecesDescription,
DOCUMENT_ESTATE_SEPARATION_PIECES.UNIT_ID AS EstateSeprationPiecesUnitId,
(SELECT ES.TITLE FROM ESTATE_SECTION es WHERE ES.ID = DOCUMENT_ESTATE_SEPARATION_PIECES.ESTATE_SECTION_ID ) AS EstateSeprationPieceSectionTitle,
(SELECT ES.TITLE FROM ESTATE_SUBSECTION es WHERE ES.ID = DOCUMENT_ESTATE_SEPARATION_PIECES.ESTATE_SUBSECTION_ID ) AS EstateSeprationPieceSubSectionTitle,
DOCUMENT_ESTATE_SEPARATION_PIECES.SECONDARY_PLAQUE AS EstateSeprationPieceSecondaryPlaque,
DOCUMENT_ESTATE_SEPARATION_PIECES.BASIC_PLAQUE AS EstateSeprationPieceBasicPlaque,
DOCUMENT_ESTATE_SEPARATION_PIECES.DIVIDED_FROM_SECONDARY_PLAQUE AS EstateSeprationPieceDividedFromSecondaryPlaque,
DOCUMENT_ESTATE_SEPARATION_PIECES.PLAQUE_TEXT AS EstateSeprationPiecePlaqueText ,
DOCUMENT_ESTATE_SEPARATION_PIECES.DOCUMENT_ESTATE_SEPARATION_PIECE_KIND_ID AS EstateSeprationPieceKindId,
CAST(DOCUMENT_ESTATE_SEPARATION_PIECES_QUOTA.DOCUMENT_PERSON_ID AS VARCHAR2(100)) AS EstateSeprationPersonId ,
DOCUMENT_ESTATE_SEPARATION_PIECES_QUOTA.DETAIL_QUOTA AS EstateSeprationPieceDetailQuota,
DOCUMENT_ESTATE_SEPARATION_PIECES_QUOTA.TOTAL_QUOTA AS EstateSeprationPieceTotalQuota,
(SELECT DETAIL_QUOTA FROM DOCUMENT_VEHICLE_QUOTA  WHERE DOCUMENT_VEHICLE_QUOTA.DOCUMENT_VEHICLE_ID =  DOCUMENT_VEHICLE.ID AND DOCUMENT_PERSON_ID = MAIN_DOCUMENT_PERSON.ID ) AS VehicleQuotaDetailQuota,
(SELECT TOTAL_QUOTA FROM DOCUMENT_VEHICLE_QUOTA  WHERE DOCUMENT_VEHICLE_QUOTA.DOCUMENT_VEHICLE_ID =  DOCUMENT_VEHICLE.ID AND DOCUMENT_PERSON_ID = MAIN_DOCUMENT_PERSON.ID  ) AS VehicleQuotaTotalQuota,
(SELECT QUOTA_TEXT FROM DOCUMENT_VEHICLE_QUOTA  WHERE DOCUMENT_VEHICLE_QUOTA.DOCUMENT_VEHICLE_ID =  DOCUMENT_VEHICLE.ID AND DOCUMENT_PERSON_ID = MAIN_DOCUMENT_PERSON.ID ) AS VehicleQuotaQuotaText,
(SELECT CAST(DOCUMENT_PERSON_ID AS VARCHAR2(100)) FROM DOCUMENT_VEHICLE_QUOTA  WHERE DOCUMENT_VEHICLE_QUOTA.DOCUMENT_VEHICLE_ID =  DOCUMENT_VEHICLE.ID AND DOCUMENT_PERSON_ID = MAIN_DOCUMENT_PERSON.ID ) AS VehicleQuotaPersonId,
(SELECT SELL_DETAIL_QUOTA FROM DOCUMENT_VEHICLE_QUOTA_DETAILS WHERE DOCUMENT_VEHICLE_ID = DOCUMENT_VEHICLE.ID AND DOCUMENT_PERSON_SELLER_ID = MAIN_DOCUMENT_PERSON.ID) AS VehicleQuotaDetailSellerDetailQuota,
(SELECT SELL_TOTAL_QUOTA FROM DOCUMENT_VEHICLE_QUOTA_DETAILS WHERE DOCUMENT_VEHICLE_ID = DOCUMENT_VEHICLE.ID AND DOCUMENT_PERSON_SELLER_ID = MAIN_DOCUMENT_PERSON.ID) AS VehicleQuotaDetailSellerTotalQuota,
(SELECT QUOTA_TEXT FROM DOCUMENT_VEHICLE_QUOTA_DETAILS WHERE DOCUMENT_VEHICLE_ID = DOCUMENT_VEHICLE.ID AND DOCUMENT_PERSON_SELLER_ID = MAIN_DOCUMENT_PERSON.ID) AS VehicleQuotaDetailQuotaText,
(SELECT SELL_DETAIL_QUOTA FROM DOCUMENT_VEHICLE_QUOTA_DETAILS WHERE DOCUMENT_VEHICLE_ID = DOCUMENT_VEHICLE.ID AND DOCUMENT_PERSON_BUYER_ID = MAIN_DOCUMENT_PERSON.ID) AS VehicleQuotaDetailBuyerDetailQuota,
(SELECT SELL_TOTAL_QUOTA FROM DOCUMENT_VEHICLE_QUOTA_DETAILS WHERE DOCUMENT_VEHICLE_ID = DOCUMENT_VEHICLE.ID AND DOCUMENT_PERSON_BUYER_ID = MAIN_DOCUMENT_PERSON.ID) AS VehicleQuotaDetailBuyerTotalQuota,
(SELECT CAST(DOCUMENT_VEHICLE_QUOTA_DETAILS.DOCUMENT_PERSON_SELLER_ID AS VARCHAR2(100)) FROM DOCUMENT_VEHICLE_QUOTA_DETAILS  WHERE DOCUMENT_VEHICLE_QUOTA_DETAILS.DOCUMENT_VEHICLE_ID =  DOCUMENT_VEHICLE.ID AND DOCUMENT_PERSON_SELLER_ID = MAIN_DOCUMENT_PERSON.ID ) AS VehicleQuotaDetailSellerPersonId,
(SELECT CAST(DOCUMENT_VEHICLE_QUOTA_DETAILS.DOCUMENT_PERSON_BUYER_ID AS VARCHAR2(100)) FROM DOCUMENT_VEHICLE_QUOTA_DETAILS  WHERE DOCUMENT_VEHICLE_QUOTA_DETAILS.DOCUMENT_VEHICLE_ID =  DOCUMENT_VEHICLE.ID AND DOCUMENT_PERSON_BUYER_ID = MAIN_DOCUMENT_PERSON.ID ) AS VehicleQuotaDetailBuyerPersonId
FROM DOCUMENT 
INNER JOIN DOCUMENT_TYPE  ON DOCUMENT.DOCUMENT_TYPE_ID = DOCUMENT_TYPE.ID 
LEFT JOIN  DOCUMENT_PERSON  MAIN_DOCUMENT_PERSON ON DOCUMENT.ID = MAIN_DOCUMENT_PERSON.DOCUMENT_ID
LEFT JOIN PERSON_FINGERPRINT ON MAIN_DOCUMENT_PERSON.ID = PERSON_FINGERPRINT.PERSON_FINGERPRINT_USE_CASE_ID
INNER JOIN DOCUMENT_INFO_CONFIRM  ON DOCUMENT.ID =  DOCUMENT_INFO_CONFIRM.DOCUMENT_ID
INNER JOIN DOCUMENT_INFO_TEXT  ON DOCUMENT.ID = DOCUMENT_INFO_TEXT.DOCUMENT_ID  
INNER JOIN DOCUMENT_INFO_OTHER  ON DOCUMENT.ID = DOCUMENT_INFO_OTHER.DOCUMENT_ID
LEFT JOIN DOCUMENT_INFO_JUDGEMENT  ON DOCUMENT.ID = DOCUMENT_INFO_JUDGEMENT.DOCUMENT_ID
LEFT JOIN DOCUMENT_JUDGEMENT_TYPE  ON DOCUMENT_INFO_JUDGEMENT.DOCUMENT_JUDGEMENT_TYPE_ID = DOCUMENT_JUDGEMENT_TYPE.ID 
LEFT JOIN DOCUMENT_PERSON_TYPE  ON MAIN_DOCUMENT_PERSON.DOCUMENT_PERSON_TYPE_ID = DOCUMENT_PERSON_TYPE.ID
LEFT JOIN DOCUMENT_ESTATE ON DOCUMENT.ID = DOCUMENT_ESTATE.DOCUMENT_ID
LEFT JOIN DOCUMENT_ESTATE_ATTACHMENT ON DOCUMENT_ESTATE.ID = DOCUMENT_ESTATE_ATTACHMENT.DOCUMENT_ESTATE_ID
LEFT JOIN DOCUMENT_ESTATE_TYPE ON DOCUMENT_ESTATE.DOCUMENT_ESTATE_TYPE_ID = DOCUMENT_ESTATE_TYPE.ID
LEFT JOIN DOCUMENT_PERSON_RELATED  ON MAIN_DOCUMENT_PERSON.ID = DOCUMENT_PERSON_RELATED.MAIN_PERSON_ID
LEFT JOIN RELIABLE_PERSON_REASON ON DOCUMENT_PERSON_RELATED.RELIABLE_PERSON_REASON_ID = RELIABLE_PERSON_REASON.ID
LEFT JOIN DOCUMENT_PERSON AGENT_DOCUMENT_PERSON ON DOCUMENT_PERSON_RELATED.AGENT_PERSON_ID = AGENT_DOCUMENT_PERSON.ID
LEFT JOIN AGENT_TYPE  ON DOCUMENT_PERSON_RELATED.AGENT_TYPE_ID = AGENT_TYPE.ID
LEFT JOIN DOCUMENT_COST ON DOCUMENT_COST.DOCUMENT_ID =  DOCUMENT.ID 
LEFT JOIN COST_TYPE  ON DOCUMENT_COST.COST_TYPE_ID = COST_TYPE.ID
LEFT JOIN DOCUMENT_VEHICLE ON DOCUMENT.ID = DOCUMENT_VEHICLE.DOCUMENT_ID
LEFT JOIN DOCUMENT_VEHICLE_TIP  ON DOCUMENT_VEHICLE.DOCUMENT_VEHICLE_TIP_ID = DOCUMENT_VEHICLE_TIP.ID
LEFT JOIN DOCUMENT_ESTATE_SEPARATION_PIECES ON DOCUMENT.ID = DOCUMENT_ESTATE_SEPARATION_PIECES.DOCUMENT_ID
AND DOCUMENT_ESTATE.ID = DOCUMENT_ESTATE_SEPARATION_PIECES.DOCUMENT_ESTATE_ID
LEFT JOIN DOCUMENT_ESTATE_SEPARATION_PIECES_QUOTA ON DOCUMENT_ESTATE_SEPARATION_PIECES.ID = DOCUMENT_ESTATE_SEPARATION_PIECES_QUOTA.DOCUMENT_ESTATE_SEPARATION_PIECES_ID
LEFT JOIN ESTATE_PIECE_TYPE ON DOCUMENT_ESTATE_SEPARATION_PIECES.ESTATE_PIECE_TYPE_ID = ESTATE_PIECE_TYPE.ID
LEFT JOIN DOCUMENT_INQUIRY ON DOCUMENT_INQUIRY.DOCUMENT_ID = DOCUMENT.ID
WHERE  DOCUMENT.ID = '{0}'", id);
            DocumentReportViewModel documentReportViewModel = new DocumentReportViewModel();
            var queryResult = await _connection.QueryAsync<DocumentReportItem>(mainQuery);
            documentReportViewModel.documentReportItems = queryResult.ToList();

            return documentReportViewModel;
        }
    }
}
